#!/usr/bin/env python3
"""Pin the locally fetched main migration set; never contacts a database or network.

`V…__….sql.conf` files are Flyway per-script configuration for the migration of the same name, not
migrations: they are skipped (and named on stderr). `--stdout` prints the list instead of writing it,
e.g. for a dry run over another ref; main-migrations.txt describes production and is only raised
after the rollout.
"""
import argparse
from pathlib import Path
import re
import subprocess
import sys


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


ROOT = Path(__file__).resolve().parents[3]
MIGRATIONS = "services/api/src/main/resources/db/migration"
OUTPUT = ROOT / "services/api/src/test/resources/migration/main-migrations.txt"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--ref", default="origin/main")
modus = parser.add_mutually_exclusive_group()
modus.add_argument("--check", action="store_true", help="fail if main-migrations.txt differs")
modus.add_argument("--stdout", action="store_true", help="print the list; write nothing")
args = parser.parse_args()
commit = git("rev-parse", "--verify", args.ref + "^{commit}")
files = git("ls-tree", "-r", "--name-only", commit, "--", MIGRATIONS).splitlines()
names = [Path(file).name for file in files]
configs = [name for name in names if name.endswith(".sql.conf")]
names = [name for name in names if not name.endswith(".sql.conf")]
for config in configs:
    if config.removesuffix(".conf") not in names:
        raise SystemExit(f"Flyway script configuration without its migration: {config}")
    print(f"skipped Flyway script configuration (not a migration): {config}", file=sys.stderr)
if not names or any(not re.fullmatch(r"V[0-9]+__.+\.sql", name) for name in names):
    raise SystemExit("Expected a nonempty set of versioned SQL migrations")
names.sort(key=lambda name: int(name[1:].split("__", 1)[0]))
for name in names:
    local = ROOT / MIGRATIONS / name
    original = subprocess.check_output(["git", "show", f"{commit}:{MIGRATIONS}/{name}"], cwd=ROOT)
    if not local.is_file() or local.read_bytes() != original:
        raise SystemExit(f"main migration missing or changed locally: {name}")
content = ("# Generated by services/api/tools/update-main-migrations.py; do not edit.\n"
           f"# main commit: {commit}\n" + "\n".join(names) + "\n")
if args.stdout:
    sys.stdout.write(content)
elif args.check:
    if not OUTPUT.is_file() or OUTPUT.read_text() != content:
        raise SystemExit("main migration list is stale; regenerate after main -> uems merge")
else:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
print(f"{len(names)} main migrations at {commit}", file=sys.stderr if args.stdout else sys.stdout)
