#!/usr/bin/env python3
"""Package deterministic runtime derivatives of the canonical catalog.

The full catalog remains the only authored truth.  Edge needs only access,
decode, cadence and aggregation facts; Postgres needs only aggregation facts.
Both files are generated together and checked in so production builds/tests do
not require Python or access outside their Docker build context.

Both derivatives carry the RUNTIME version (``RUNTIME_VERSION``), not the content
version: a content version that changes nothing the box or the writer reads
(``validate.py`` proves it) leaves both files byte-identical, so no box on an
older edge release ever sees a foreign ``catalog_version``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from cataloglib import CATALOG_VERSION, EDGE_FIELDS, ROOT, canonical_json_bytes


REPO = ROOT.parents[1]
SOURCE = ROOT / "dist" / f"measurement-point-catalog-{CATALOG_VERSION}.json"
EDGE = REPO / "edge-app" / "nodered" / "measurements" / "catalog.json"
MIGRATIONS = REPO / "services" / "api" / "src" / "main" / "resources" / "db" / "migration"
# ⚠ Eine angewandte Migration ist unveränderlich: jeder Laufzeitstand bekommt seine EIGENE
# Metadaten-Migration. Wer RUNTIME_VERSION hebt, trägt hier eine neue, datums-versionierte
# Datei ein — nie die alte umschreiben.
SQL_BY_RUNTIME_VERSION = {
    "2026.08.26.3": "V20260853010000__measurement_catalog_metadata_slice9_r2.sql",
}


def outputs() -> tuple[bytes, bytes]:
    catalog = json.loads(SOURCE.read_text(encoding="utf-8"))
    runtime = catalog["runtime_catalog_version"]
    points = [{key: (runtime if key == "catalog_version" else point[key])
               for key in EDGE_FIELDS if key in point}
              for point in catalog["points"]]
    edge = canonical_json_bytes({
        "schema_version": "1.0",
        "catalog_version": runtime,
        "points": points,
    })

    rows = []
    for point in catalog["points"]:
        key = point["point_key"].replace("'", "''")
        cadence = point["long_term_cadence_s"]
        rows.append("('%s','%s','%s',%s)" % (
            runtime, key, point["aggregation_kind"],
            "NULL" if cadence is None else str(cadence)))
    sql = (
        "-- GENERATED by catalog/measurement-points/tools/package_edge_runtime.py.\n"
        "-- Do not edit; update the canonical catalog and regenerate.\n"
        "INSERT INTO measurement_catalog_point_metadata\n"
        "  (catalog_version, point_key, aggregation_kind, long_term_cadence_s) VALUES\n  "
        + ",\n  ".join(rows)
        + "\nON CONFLICT (catalog_version, point_key) DO NOTHING;\n"
    ).encode("utf-8")
    return edge, sql


def sql_path() -> Path:
    runtime = json.loads(SOURCE.read_text(encoding="utf-8"))["runtime_catalog_version"]
    if runtime not in SQL_BY_RUNTIME_VERSION:
        raise SystemExit(f"runtime catalog {runtime} has no metadata migration in SQL_BY_RUNTIME_VERSION")
    return MIGRATIONS / SQL_BY_RUNTIME_VERSION[runtime]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    edge, sql = outputs()
    expected = ((EDGE, edge), (sql_path(), sql))
    if args.check:
        stale = [str(path.relative_to(REPO)) for path, raw in expected
                 if not path.exists() or path.read_bytes() != raw]
        if stale:
            raise SystemExit("runtime catalog derivatives are stale: " + ", ".join(stale))
        print(f"runtime derivatives of catalog {CATALOG_VERSION} match its runtime version")
        return 0
    for path, raw in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
    print(f"packaged {len(json.loads(edge)['points'])} runtime points")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
