import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { api } from '../api';
import { setSelbstauskunft } from '../rollen';
import { rechteSeed } from '../test/rollenFixtures';
import { ahrenbergHeute, FIXTURE_IDS } from '../test/standorteFixtures';
import { c1 } from '../test/geraetHerkunftFixtures';
import { controllerVorschau, CONTROLLER_AM } from '../test/controllerwechselFixtures';
import { ControllerwechselDialog } from './ControllerwechselDialog';
afterEach(() => vi.restoreAllMocks());
beforeEach(() => setSelbstauskunft(rechteSeed('JW').me));
it('C1 bestätigt alle vier Messstellen vor genau einem POST; Serverfehler erhält die Eingaben', async () => {
  vi.spyOn(api, 'standorte').mockResolvedValue(ahrenbergHeute());
  vi.spyOn(api, 'controllerwechselVorschau').mockResolvedValue(controllerVorschau());
  const post = vi.spyOn(api, 'geraetAustauschen').mockRejectedValue(new Error('Bitte Folgen erneut prüfen.'));
  render(<ControllerwechselDialog geraet={c1()} anlageId={FIXTURE_IDS.an2} jetzt={CONTROLLER_AM} onClose={vi.fn()} onGewechselt={vi.fn()} />);
  await screen.findByLabelText('Endstand MS-10 (kWh, optional)');
  fireEvent.change(screen.getByLabelText('Endstand MS-10 (kWh, optional)'), { target: { value: '1.234,5' } });
  fireEvent.click(screen.getAllByLabelText('Karte übernommen')[3]);
  fireEvent.click(screen.getByRole('button', { name: 'Folgen prüfen' }));
  const folgen = screen.getByRole('region', { name: 'Folgen des Controllerwechsels' });
  for (const ms of ['MS-10', 'MS-11', 'MS-12', 'MS-13']) expect(folgen).toHaveTextContent(ms);
  expect(folgen).toHaveTextContent('EK-4: ebenfalls neu'); expect(post).not.toHaveBeenCalled();
  const knopf = screen.getByRole('button', { name: 'Controllerwechsel eintragen' }); fireEvent.click(knopf); fireEvent.click(knopf);
  await waitFor(() => expect(post).toHaveBeenCalledTimes(1));
  await screen.findByText('Bitte Folgen erneut prüfen.');
  expect(screen.getByLabelText('Endstand MS-10 (kWh, optional)')).toHaveValue('1.234,5');
  expect(post.mock.calls[0][1].karten_uebernommen).toHaveLength(3);
});
