'use strict';
/*
 * build-flows.js - deterministic generator for flows.json.
 *
 * flows.json is Node-RED's self-contained flow document; its function nodes
 * carry COPIES of the repo codecs (a flow cannot `require` a repo file at
 * runtime). Hand-editing the escaped JSON strings is error-prone, so this
 * script assembles the document from readable sources and is IDEMPOTENT
 * (re-running reproduces flows.json byte-for-byte). It preserves two things
 * VERBATIM from the existing flows.json:
 *   - the "SunSpec (Simulator)" tab + config nodes (kept for the hardware-free
 *     e2e), and
 *   - the Deye Solarman-V5 reader + decoder function bodies (`auto-solarman` /
 *     `auto-deye-decode`, synced copies of deye/solarman-v5.js +
 *     deye/deye-decode.js) - so those bodies are edited in the module + the
 *     flow node, and the generator carries them through untouched.
 * Everything else (the router, the store/idle nodes, the generic Modbus reader
 * + decoder, wiring, layout) is authored HERE as readable JS.
 *
 * Run: node build-flows.js   (writes flows.json; idempotent). flows.json is the
 * committed artifact, so the generator is a reformatter, not a bootstrap.
 */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'flows.json');
const prev = JSON.parse(fs.readFileSync(OUT, 'utf8'));
const byId = Object.fromEntries(prev.map((n) => [n.id, n]));

const need = (id) => {
  if (!byId[id]) throw new Error('build-flows.js: node "' + id + '" missing from flows.json (the generator preserves it; do not delete it by hand)');
  return byId[id];
};

// --- keep verbatim: config nodes + the sim READ nodes ------------------------
const keepConfig = ['cfg-vp-core', 'cfg-mb-sim'].map(need);
// The Simulator tab's READ path is preserved verbatim (poll -> FC3 read ->
// decode -> telemetry/status); only its WRITE path is replaced by the control
// adapter (controlRoute + write/readback), authored below.
const simReadNodes = ['sim-note', 'sim-poll', 'sim-read', 'sim-decode', 'sim-telemetrie', 'sim-status', 'sim-linkwatch'].map(need);
const simTab = need('tab-sim');

// --- reuse verbatim: the tested Deye reader + decoder function bodies ---------
const solarmanFunc = need('auto-solarman').func; // Solarman-V5 socket reader (copy of deye/solarman-v5.js)
const deyeDecodeFunc = need('auto-deye-decode').func; // register -> reading (copy of deye/deye-decode.js)

// --- the self-wiring tab -----------------------------------------------------
const TAB = 'tab-auto';

const routerFunc = [
  "// Router / Leseplan - das Herzstueck der Selbstverdrahtung: liest die aktive",
  "// Wechselrichter-Auswahl aus dem Flow-Kontext (von vp-inverter-config gesetzt)",
  "// und waehlt GENAU EINEN Lesepfad. Synchron gehalten mit",
  "// edge-app/nodered/inverter-routing.js (route) + den Registerkarten aus",
  "// deye/deye-decode.js und modbus-tcp.js.",
  "//   Ausgang 1: Deye Solarman-V5       (msg.deye)",
  "//   Ausgang 2: generisches Modbus     (msg.mb)",
  "//   Ausgang 3: Fronius Solar API      (msg.fronius)",
  "//   Ausgang 4: Fronius SunSpec-Modbus (msg.sunspec)",
  "//   Ausgang 5: untaetig               (keine/unbekannte Auswahl)",
  "const DEYE_READS = {",
  "  string:    [{ start: 0x0050, count: 0x0002 }],",
  "  hybrid_1p: [{ start: 0x00a9, count: 0x0016 }],",
  // hybrid_3p: device-identity register 0x0000 (LV/HV scale class) + the widened
  // measurement block 0x024C..0x02C4 (121 regs) covering the External-CT grid
  // pair 0x026B/0x02C4 (the connection point) plus the 32-bit alias/load words.
  // Must equal deye-decode.planReads({family:'hybrid_3p'}) (flows-sync guard).
  "  hybrid_3p: [{ start: 0x0000, count: 0x0001 }, { start: 0x024c, count: 0x0079 }],",
  "  micro:     [{ start: 0x0056, count: 0x0002 }]",
  "};",
  "const MODBUS_PROFILES = { sunspec: { fc: 3, addr: 0, count: 9 } };",
  "const FRONIUS_FAMILIES = { fronius_solar_api: true };",
  "const FRONIUS_POWERFLOW_PATH = '/solar_api/v1/GetPowerFlowRealtimeData.fcgi';",
  "const num = (v, d) => { const n = typeof v === 'string' ? Number(v.trim()) : v; return (typeof n === 'number' && isFinite(n)) ? n : d; };",
  "const idle = (reason) => { node.status({ fill: 'grey', shape: 'ring', text: reason }); msg.idle = reason; return [null, null, null, null, msg]; };",
  "const sel = flow.get('inverter_config');",
  "if (!sel) return idle('keine Auswahl');",
  "const conn = sel.connection || {};",
  "const ip = (typeof conn.ip === 'string' ? conn.ip : '').trim();",
  "if (!ip) return idle('keine IP-Adresse');",
  "if (sel.communication === 'solarman_v5') {",
  "  const reads = DEYE_READS[sel.family];",
  "  if (!reads) return idle('unbekannte Deye-Familie: ' + sel.family);",
  "  const serial = conn.serial;",
  "  if (serial === undefined || serial === null || serial === '' || !(Number(serial) > 0)) return idle('Datenlogger-Seriennummer fehlt');",
  "  const port = num(conn.port, 8899);",
  "  const cfg = {",
  "    ip, port, serial,",
  "    mb_slave_id: num(conn.mb_slave_id, 1),",
  "    family: sel.family,",
  "    invert_grid_sign: !!conn.invert_grid_sign,",
  "    invert_batt_sign: !!conn.invert_batt_sign,",
  // power_scale is now a MANUAL OVERRIDE / fallback (0 = auto-detect from 0x0000);
  // pass it through unchanged so the decoder resolves the LV/HV scale.
  "    power_scale: num(conn.power_scale, 0)",
  "  };",
  "  msg.deye = { cfg, target: ip + ':' + port, reads: reads.map((r) => ({ start: r.start, count: r.count })), i: 0, blocks: [] };",
  "  node.status({ fill: 'blue', shape: 'dot', text: 'Deye ' + sel.family + ' -> Solarman-V5' });",
  "  return [msg, null, null, null, null];",
  "}",
  "if (sel.communication === 'modbus_tcp') {",
  "  const read = MODBUS_PROFILES[sel.family];",
  "  if (!read) return idle('unbekanntes Modbus-Profil: ' + sel.family);",
  "  const port = num(conn.port, 502);",
  "  msg.mb = { conn: { ip, port, unit_id: num(conn.unit_id, 1) }, profile: sel.family, read: { fc: read.fc, addr: read.addr, count: read.count }, target: ip + ':' + port };",
  "  node.status({ fill: 'blue', shape: 'dot', text: 'Modbus ' + sel.family + ' @ ' + ip + ':' + port });",
  "  return [null, msg, null, null, null];",
  "}",
  "if (sel.communication === 'fronius_solar_api') {",
  "  if (!FRONIUS_FAMILIES[sel.family]) return idle('unbekannte Fronius-Familie: ' + sel.family);",
  "  const port = num(conn.port, 80);",
  "  const insecure = !!conn.insecure_tls;",
  "  const scheme = insecure ? 'https' : 'http';",
  "  msg.fronius = { url: scheme + '://' + ip + ':' + port + FRONIUS_POWERFLOW_PATH, scheme, insecure_tls: insecure, invert_grid_sign: !!conn.invert_grid_sign, target: ip + ':' + port };",
  "  node.status({ fill: 'blue', shape: 'dot', text: 'Fronius Solar API @ ' + ip + ':' + port });",
  "  return [null, null, msg, null, null];",
  "}",
  "if (sel.communication === 'fronius_sunspec') {",
  "  const port = num(conn.port, 502);",
  "  const modelType = (conn.model_type === 'float' || conn.model_type === 'int_sf') ? conn.model_type : 'auto';",
  "  msg.sunspec = { conn: { ip, port, unit_id: num(conn.unit_id, 1), invert_grid_sign: !!conn.invert_grid_sign, model_type: modelType }, target: ip + ':' + port };",
  "  node.status({ fill: 'blue', shape: 'dot', text: 'Fronius SunSpec @ ' + ip + ':' + port });",
  "  return [null, null, null, msg, null];",
  "}",
  "return idle('unbekannte Kommunikationsmethode');",
].join('\n');

const storeFunc = [
  "// Uebernimmt die im Edge-App-Portal getroffene Wechselrichter-Auswahl",
  "// (retained auf edge/inverter/config, von vp-inverter-config geparst) in den",
  "// Flow-Kontext. Der Router unten liest sie bei jedem Poll - so verdrahtet sich",
  "// der Flow selbst, ohne Edit pro Kunde. payload === null => Auswahl geloescht.",
  "const sel = msg.payload || null;",
  "flow.set('inverter_config', sel);",
  "if (sel) {",
  "  node.status({ fill: 'green', shape: 'dot', text: (sel.label || sel.brand || sel.family) + ' (' + sel.communication + ')' });",
  "} else {",
  "  node.status({ fill: 'grey', shape: 'ring', text: 'Auswahl zurueckgesetzt' });",
  "}",
  "return null;",
].join('\n');

const modbusReadFunc = [
  "// Generischer Modbus-TCP-Leser (FC3, Holding Registers): eine geordnete",
  "// TCP-Verbindung pro Poll, ein Registerblock, TCP-Segmente reassembliert.",
  "// Traegt eine KOPIE des Codecs aus edge-app/nodered/modbus-tcp.js",
  "// (buildReadRequest/expectedFrameLength/parseReadResponse) - beide synchron",
  "// halten (ein Node-RED-Flow ist self-contained JSON und kann keine Repo-Datei",
  "// zur Laufzeit requiren). Quelle der Wahrheit + Offline-Tests: modbus-tcp.js.",
  "const net = global.get('net');",
  "if (!net) { node.status({ fill: 'red', shape: 'ring', text: 'net fehlt (settings.js)' }); node.error('functionGlobalContext.net in settings.js setzen', msg); return null; }",
  "const mb = msg.mb;",
  "if (!mb) return null;",
  "const conn = mb.conn;",
  "const unitId = conn.unit_id || 1;",
  "const timeoutMs = conn.timeout_ms || 5000;",
  "const buildReq = (txid, addr, count) => { const b = Buffer.alloc(12); b.writeUInt16BE(txid & 0xffff, 0); b.writeUInt16BE(0, 2); b.writeUInt16BE(6, 4); b[6] = unitId & 0xff; b[7] = 0x03; b.writeUInt16BE(addr & 0xffff, 8); b.writeUInt16BE(count & 0xffff, 10); return b; };",
  "const frameLen = (buf) => (buf.length < 6 ? null : 6 + buf.readUInt16BE(4));",
  "const parseResp = (buf, txid) => {",
  "  if (buf.length < 9) throw new Error('Antwort zu kurz');",
  "  if (buf.readUInt16BE(2) !== 0) throw new Error('Protokoll-ID');",
  "  if (buf.readUInt16BE(0) !== (txid & 0xffff)) throw new Error('Transaktions-ID weicht ab');",
  "  const fn = buf[7];",
  "  if (fn & 0x80) throw new Error('Modbus-Ausnahme 0x' + (buf[8] || 0).toString(16));",
  "  if (fn !== 0x03) throw new Error('Modbus-Funktion 0x' + fn.toString(16));",
  "  const bc = buf[8];",
  "  if (bc <= 0 || buf.length < 9 + bc) throw new Error('Nutzlast unvollstaendig');",
  "  const regs = []; for (let i = 0; i < bc >> 1; i++) regs.push(buf.readUInt16BE(9 + i * 2)); return regs;",
  "};",
  "let txid = context.get('txid') || 0;",
  "return new Promise((resolve) => {",
  "  const sock = new net.Socket();",
  "  sock.setNoDelay(true);",
  "  let done = false;",
  "  let acc = Buffer.alloc(0);",
  "  const finish = (err) => { if (done) return; done = true; try { sock.destroy(); } catch (e) { /* ignore */ } if (err) { node.status({ fill: 'red', shape: 'ring', text: 'Modbus: ' + err.message }); resolve(null); } else { resolve(msg); } };",
  "  const t = setTimeout(() => finish(new Error('Timeout')), timeoutMs);",
  "  txid = (txid + 1) & 0xffff; context.set('txid', txid);",
  "  sock.once('error', (e) => { clearTimeout(t); finish(e); });",
  "  sock.connect(conn.port || 502, conn.ip, () => {",
  "    sock.on('data', (chunk) => {",
  "      acc = Buffer.concat([acc, chunk]);",
  "      const need = frameLen(acc);",
  "      if (need !== null && acc.length >= need) { clearTimeout(t); try { mb.regs = parseResp(acc.slice(0, need), txid); finish(); } catch (e) { finish(e); } }",
  "    });",
  "    sock.write(buildReq(txid, mb.read.addr, mb.read.count));",
  "  });",
  "});",
].join('\n');

const modbusDecodeFunc = [
  "// Decodiert den Modbus-Block laut Profil in die flache edge/telemetry-Nachricht.",
  "// Traegt eine KOPIE der PROFILES aus edge-app/nodered/modbus-tcp.js - synchron",
  "// halten. Ausgang 1: Messwerte fuer vp-telemetrie; Ausgang 2: true als Link-",
  "// Lebenszeichen. Das Profil 'sunspec' entspricht dem kompakten Block des",
  "// SunSpec-Simulators (edge/sim/sunspec-sim.js), FC3 Adr. 0..8.",
  "const mb = msg.mb;",
  "if (!mb || !Array.isArray(mb.regs)) { node.status({ fill: 'red', shape: 'ring', text: 'keine Register' }); return null; }",
  "const s16 = (v) => { v &= 0xffff; return v > 0x7fff ? v - 0x10000 : v; };",
  "const r3 = (x) => Math.round(x * 1000) / 1000;",
  "const r1 = (x) => Math.round(x * 10) / 10;",
  "const PROFILES = {",
  "  sunspec: (regs) => {",
  "    if (regs.length < 7) return null;",
  "    const gridKw = s16(regs[0]) / 100;   // + Bezug / - Einspeisung",
  "    const pvKw = s16(regs[1]) / 100;",
  "    const loadKw = s16(regs[2]) / 100;",
  "    const socPct = regs[4] / 10;",
  "    const wmax = regs[5] / 100;          // beobachtete §14a-Begrenzung in %",
  "    const gridConn = regs[6] / 100;",
  "    const reading = { ts: new Date().toISOString(), power_kw: r3(gridKw), pv_power_kw: r3(pvKw), load_kw: r3(loadKw), soc_pct: r1(socPct), grid_limit_kw: r3((wmax / 100) * gridConn) };",
  "    return { reading, batt_kw: r3(s16(regs[3]) / 100) };",
  "  }",
  "};",
  "const dec = PROFILES[mb.profile];",
  "if (!dec) { node.status({ fill: 'red', shape: 'ring', text: 'unbekanntes Profil: ' + mb.profile }); return null; }",
  "const out = dec(mb.regs);",
  "if (!out) { node.status({ fill: 'yellow', shape: 'ring', text: 'keine Messwerte decodiert' }); return null; }",
  "// Gemessene Batterieleistung (+Laden/-Entladen) NUR auf den lokalen Bus: der Core",
  "// bildet daraus mit einem Netz-Zaehler den echten Hausverbrauch (Leistungsbilanz);",
  "// in die Cloud wird sie nie veroeffentlicht (dort bleibt battery aus der Bilanz).",
  "if (out.batt_kw !== undefined) out.reading.battery_power_kw = out.batt_kw;",
  "const pv = out.reading.pv_power_kw !== undefined ? out.reading.pv_power_kw.toFixed(1) : '?';",
  "const soc = out.reading.soc_pct !== undefined ? (', SoC ' + out.reading.soc_pct.toFixed(0) + ' %') : '';",
  "node.status({ fill: 'green', shape: 'dot', text: 'pv ' + pv + ' kW' + soc });",
  "return [{ payload: out.reading }, { payload: true }];",
].join('\n');

const froniusReadFunc = [
  "// Fronius Solar API lesen: EIN HTTP(S)-GET auf GetPowerFlowRealtimeData.fcgi",
  "// (Solar API v1) - wie Home Assistant Fronius liest. Traegt KEINE Decode-Logik",
  "// (der naechste Knoten decodiert), nur den HTTP-Client. https +",
  "// rejectUnauthorized:false NUR bei insecure_tls (GEN24-Firmware, die auf HTTPS",
  "// mit selbstsigniertem Zertifikat umleitet). Jeder Fehler (Verbindung, Timeout,",
  "// kein JSON, HTTP>=400) -> null = idle-sicher, nie fabriziert. Quelle der",
  "// Wahrheit fuer die URL/Decode: edge-app/nodered/fronius/solar-api.js.",
  "const http = global.get('http');",
  "const https = global.get('https');",
  "if (!http || !https) { node.status({ fill: 'red', shape: 'ring', text: 'http/https fehlt (settings.js)' }); node.error('functionGlobalContext.http/https in settings.js setzen', msg); return null; }",
  "const f = msg.fronius;",
  "if (!f || !f.url) return null;",
  "const lib = f.scheme === 'https' ? https : http;",
  "const timeoutMs = 5000;",
  "return new Promise((resolve) => {",
  "  let done = false;",
  "  const finish = (ok) => { if (done) return; done = true; resolve(ok); };",
  "  const opts = { method: 'GET', timeout: timeoutMs };",
  "  if (f.scheme === 'https') opts.rejectUnauthorized = f.insecure_tls ? false : true;",
  "  let req;",
  "  try {",
  "    req = lib.request(f.url, opts, (res) => {",
  "      if (res.statusCode >= 400) { node.status({ fill: 'red', shape: 'ring', text: 'HTTP ' + res.statusCode }); res.resume(); return finish(null); }",
  "      let body = '';",
  "      res.setEncoding('utf8');",
  "      res.on('data', (c) => { body += c; if (body.length > 262144) { try { req.destroy(); } catch (e) { /* ignore */ } } });",
  "      res.on('end', () => { try { f.json = JSON.parse(body); finish(msg); } catch (e) { node.status({ fill: 'red', shape: 'ring', text: 'kein JSON' }); finish(null); } });",
  "    });",
  "  } catch (e) { node.status({ fill: 'red', shape: 'ring', text: 'Fronius: ' + e.message }); return finish(null); }",
  "  req.on('error', (e) => { node.status({ fill: 'red', shape: 'ring', text: 'Fronius: ' + e.message }); finish(null); });",
  "  req.on('timeout', () => { node.status({ fill: 'red', shape: 'ring', text: 'Timeout' }); try { req.destroy(); } catch (e) { /* ignore */ } finish(null); });",
  "  req.end();",
  "});",
].join('\n');

const froniusDecodeFunc = [
  "// Fronius PowerFlow -> flache edge/telemetry-Nachricht. Traegt eine KOPIE von",
  "// decodePowerFlow aus edge-app/nodered/fronius/solar-api.js - synchron halten",
  "// (flows-sync.test.js pinnt es). Ausgang 1: Messwerte fuer vp-telemetrie;",
  "// Ausgang 2: true als Link-Lebenszeichen. VORZEICHEN (auf echtem Geraet",
  "// PRUEFEN): power_kw = P_Grid (+Bezug/-Einspeisung, wie VoltPilot, KEINE",
  "// Invertierung noetig), load_kw = -P_Load (Fronius meldet Last negativ). Ein",
  "// fehlendes Feld -> Kanal ausgelassen (nie fabrizierte 0); SoC ausserhalb",
  "// (0,100] fallen gelassen; P_Akku nur Kalibrierung, NIE veroeffentlicht (die",
  "// Cloud leitet battery_kw aus der Leistungsbilanz ab).",
  "const f = msg.fronius;",
  "if (!f || !f.json) { node.status({ fill: 'red', shape: 'ring', text: 'keine Antwort' }); return null; }",
  "const r3 = (x) => Math.round(x * 1000) / 1000;",
  "const r1 = (x) => Math.round(x * 10) / 10;",
  "const num = (v) => (typeof v === 'number' && isFinite(v) ? v : null);",
  "const socOk = (p) => (typeof p === 'number' && isFinite(p) && p > 0 && p <= 100);",
  "const decodePowerFlow = (json, opts) => {",
  "  opts = opts || {};",
  "  if (json == null || typeof json !== 'object') return null;",
  "  const body = json.Body;",
  "  const data = body && typeof body === 'object' ? body.Data : null;",
  "  if (!data || typeof data !== 'object') return null;",
  "  const head = json.Head;",
  "  if (head && head.Status && typeof head.Status.Code === 'number' && head.Status.Code !== 0) return null;",
  "  const site = data.Site;",
  "  if (!site || typeof site !== 'object') return null;",
  "  const reading = {};",
  "  const pGrid = num(site.P_Grid);",
  "  if (pGrid !== null) { const sign = opts.invertGridSign ? -1 : 1; reading.power_kw = r3((sign * pGrid) / 1000); }",
  "  const pPv = num(site.P_PV);",
  "  if (pPv !== null) reading.pv_power_kw = r3(Math.max(0, pPv) / 1000);",
  "  const pLoad = num(site.P_Load);",
  "  if (pLoad !== null) reading.load_kw = r3(Math.max(0, -pLoad) / 1000);",
  "  let soc = null;",
  "  const inv = data.Inverters;",
  "  if (inv && typeof inv === 'object') { const first = inv['1']; if (first && typeof first === 'object') soc = num(first.SOC); }",
  "  if (socOk(soc)) reading.soc_pct = r1(soc);",
  "  if (Object.keys(reading).length === 0) return null;",
  "  const pAkku = num(site.P_Akku);",
  "  const battKw = pAkku === null ? null : r3(pAkku / 1000);",
  "  return { reading, battKw };",
  "};",
  "const out = decodePowerFlow(f.json, { invertGridSign: !!f.invert_grid_sign });",
  "if (!out) { node.status({ fill: 'yellow', shape: 'ring', text: 'keine Messwerte' }); return null; }",
  "const reading = Object.assign({ ts: new Date().toISOString() }, out.reading);",
  "const pv = reading.pv_power_kw !== undefined ? reading.pv_power_kw.toFixed(1) : '?';",
  "const soc = reading.soc_pct !== undefined ? (', SoC ' + reading.soc_pct.toFixed(0) + ' %') : '';",
  "node.status({ fill: 'green', shape: 'dot', text: 'pv ' + pv + ' kW' + soc });",
  "return [{ payload: reading }, { payload: true }];",
].join('\n');

const idleFunc = [
  "// Untaetig: keine oder unbekannte Auswahl. Setzt nur den Knotenstatus als",
  "// sichtbaren Hinweis - es wird KEIN edge/status veroeffentlicht (sonst wuerde",
  "// es im reinen Simulator-Betrieb mit dem Link-Status des Simulator-Tabs",
  "// kollidieren). Sobald eine gueltige Auswahl retained eintrifft, laeuft der",
  "// passende Lesepfad automatisch an.",
  "node.status({ fill: 'grey', shape: 'ring', text: msg.idle || 'keine Auswahl' });",
  "return null;",
].join('\n');

// --- control path (write + readback) -----------------------------------------
//
// The write-side twin of the read self-wiring. `controlRouteSource` is a synced
// COPY of inverter-control-routing.js controlRoute() (a Node-RED flow cannot
// `require` a repo file); flows-sync.test.js pins the two together. SAFETY:
// controlRoute keeps writes EMPTY unless control_enabled (the core kill-switch,
// default off) AND the family is in the certified allowlist ('sunspec' only -
// Deye stays read-only until bench-verified). See report §4/§6.
const controlRouteSource = [
  "function controlRoute(selection, setpoint, opts) {",
  "  opts = opts || {};",
  "  var idle = function (reason) { return { adapter: 'idle', family: '', certified: false, controlEnabled: false, writes: [], readbacks: [], reason: reason }; };",
  "  if (!selection) return idle('keine Auswahl');",
  "  var conn = selection.connection || {};",
  "  var ip = typeof conn.ip === 'string' ? conn.ip.trim() : '';",
  "  if (!ip) return idle('keine IP-Adresse');",
  "  if (!setpoint || typeof setpoint.battery_setpoint_kw !== 'number' || !isFinite(setpoint.battery_setpoint_kw)) return idle('kein gueltiger Sollwert');",
  "  var CERTIFIED = { sunspec: true };",
  "  var s16raw = function (kw) { return Math.round(kw * 100) & 0xffff; };",
  "  var clampPct = function (v) { return Math.max(0, Math.min(100, Math.round(v))); };",
  "  var NO_PV_LIMIT = 0xffff;",
  "  var controlEnabled = setpoint.control_enabled === true;",
  "  var family = typeof selection.family === 'string' ? selection.family.trim() : '';",
  "  var certified = CERTIFIED[family] === true;",
  "  var kw = setpoint.battery_setpoint_kw;",
  "  var pvLimitKw = (typeof setpoint.pv_limit_kw === 'number' && isFinite(setpoint.pv_limit_kw) && setpoint.pv_limit_kw >= 0) ? setpoint.pv_limit_kw : null;",
  "  // Dispatch on the CONTROL TIER (control_tier from the selection, else inferred",
  "  // from the communication - byte-identical for every catalogued brand). Tier",
  "  // decouples control from the read transport (report §1/§7.3).",
  "  var resolveTier = function (sel) {",
  "    var t = sel && sel.control_tier;",
  "    if (typeof t === 'number' && isFinite(t) && t >= 0 && t <= 3) return Math.floor(t);",
  "    if (sel && sel.communication === 'solarman_v5') return 3;",
  "    if (sel && sel.communication === 'modbus_tcp') return 1;",
  "    if (sel && sel.communication === 'fronius_solar_api') return 1;",
  "    return 0;",
  "  };",
  "  var tier = resolveTier(selection);",
  "  var comm = selection.communication;",
  "  if (tier === 2) {",
  "    // Tier-2 vendor external-EMS (Sungrow/SolarEdge) - EXTENSION POINT, Phase E.",
  "    // Never a live write; keeps a catalogued Tier-2 brand from being misread as",
  "    // a Tier-1 SunSpec device just because it reads over modbus_tcp.",
  "    var v2port = Number(conn.port) > 0 ? Number(conn.port) : 502;",
  "    return { adapter: 'vendor_ems', family: family, target: ip + ':' + v2port, connection: { ip: ip, port: v2port }, certified: false, controlEnabled: controlEnabled, writes: [], readbacks: [], planned: [], reason: 'Tier-2 Wechselrichtersteuerung (externes EMS) noch nicht implementiert' };",
  "  }",
  "  if (tier === 1 && comm === 'modbus_tcp') {",
  "    var port = Number(conn.port) > 0 ? Number(conn.port) : 502;",
  "    var unitId = Number(conn.unit_id) > 0 ? Number(conn.unit_id) : 1;",
  "    var invert = conn.invert_control_sign === true;",
  "    var battKw = invert ? -kw : kw;",
  "    var battRaw = s16raw(battKw);",
  "    var pvRaw = pvLimitKw == null ? NO_PV_LIMIT : (Math.max(0, Math.round(pvLimitKw * 100)) & 0xffff);",
  "    var planned = [",
  "      { role: 'battery_power', fc: 6, addr: 40, value: battRaw, encode: { kind: 'kw_x100_s16', scale: 100, kw: battKw }, dwell_s: 0, min_change: 0 },",
  "      { role: 'control_enable', fc: 6, addr: 41, value: 1, encode: { kind: 'flag' }, dwell_s: 0, min_change: 0 },",
  "      { role: 'pv_limit', fc: 6, addr: 42, value: pvRaw, encode: { kind: 'pv_limit_x100_u16', scale: 100, sentinel: NO_PV_LIMIT, kw: pvLimitKw }, dwell_s: 0, min_change: 0 }",
  "    ];",
  "    var readbacks = [",
  "      { role: 'battery_power', fc: 3, addr: 40, expect: battRaw, tolerance: 1 },",
  "      { role: 'control_enable', fc: 3, addr: 41, expect: 1, tolerance: 0 },",
  "      { role: 'pv_limit', fc: 3, addr: 42, expect: pvRaw, tolerance: 1 }",
  "    ];",
  "    var writeAllowed = certified && controlEnabled;",
  "    var out = { adapter: 'modbus_tcp', family: family, profile: family, target: ip + ':' + port, connection: { ip: ip, port: port, unit_id: unitId }, certified: certified, controlEnabled: controlEnabled, writes: writeAllowed ? planned : [], readbacks: readbacks, planned: planned };",
  "    if (!writeAllowed) out.reason = certified ? 'Steuerung deaktiviert (Not-Aus)' : 'Modell noch nicht freigegeben';",
  "    return out;",
  "  }",
  "  if (tier === 3 && comm === 'solarman_v5') {",
  "    // ha-solarman-sourced Deye ToU/work-mode registers (deye_p3.yaml hybrid_3p,",
  "    // deye_hybrid.yaml hybrid_1p). BENCH-PENDING: no executable writes.",
  "    var DEYE_REG = {",
  "      hybrid_3p: { workMode: 0x008e, touEnable: 0x0092, progPowerBase: 0x009a, progSocBase: 0x00a6, progChargeBase: 0x00ac, exportLimit: 0x00e7, exportLimitScale: 10 },",
  "      hybrid_1p: { workMode: 0x00f4, touEnable: 0x00f8, progPowerBase: 0x0100, progSocBase: 0x010c, progChargeBase: 0x0112, exportLimit: 0x00f5, exportLimitScale: 1 }",
  "    };",
  "    var dport = Number(conn.port) > 0 ? Number(conn.port) : 8899;",
  "    var serial = conn.serial;",
  "    var slaveId = Number(conn.mb_slave_id) > 0 ? Number(conn.mb_slave_id) : 1;",
  "    var dinvert = conn.invert_control_sign === true;",
  "    var socMin = (typeof setpoint.soc_min_pct === 'number' && isFinite(setpoint.soc_min_pct)) ? setpoint.soc_min_pct : 5;",
  "    var powerScale = Number(conn.power_scale) > 0 ? Number(conn.power_scale) : 1;",
  "    var dbase = { adapter: 'solarman_v5', family: family, target: ip + ':' + dport, connection: { ip: ip, port: dport, serial: serial, mb_slave_id: slaveId }, certified: certified, controlEnabled: controlEnabled, writes: [], readbacks: [], reason: 'Steuerung f\\u00fcr dieses Modell noch nicht freigegeben' };",
  "    var reg = Object.prototype.hasOwnProperty.call(DEYE_REG, family) ? DEYE_REG[family] : null;",
  "    if (!reg) {",
  "      var ratedKw = Number(opts.ratedKw) > 0 ? Number(opts.ratedKw) : 0;",
  "      var splanned = [];",
  "      if (pvLimitKw != null && ratedKw > 0) { splanned.push({ role: 'pv_limit', fc: 6, addr: 0x0028, value: clampPct((pvLimitKw / ratedKw) * 100), encode: { kind: 'active_power_pct', rated_kw: ratedKw, kw: pvLimitKw }, dwell_s: 900, min_change: 1, bench_pending: true }); }",
  "      dbase.planned = splanned; return dbase;",
  "    }",
  "    var dbattKw = dinvert ? -kw : kw;",
  "    var charging = dbattKw > 0;",
  "    var powerReg = Math.max(0, Math.round((Math.abs(dbattKw) * 1000) / powerScale)) & 0xffff;",
  "    var targetSoc = charging ? 100 : clampPct(socMin);",
  "    var gridChargeAllowed = setpoint.grid_charge_allowed === true;",
  "    var chargeEnum = (gridChargeAllowed && charging) ? 1 : 0;",
  "    var slot = 0;",
  "    var dplanned = [",
  "      { role: 'work_mode', fc: 6, addr: reg.workMode, value: 0, encode: { kind: 'work_mode', enum: 'export_first' }, dwell_s: 900, min_change: 0, bench_pending: true },",
  "      { role: 'tou_enable', fc: 6, addr: reg.touEnable, value: 0x00ff, encode: { kind: 'tou_mask', all_week: true }, dwell_s: 900, min_change: 0, bench_pending: true },",
  "      { role: 'battery_power', fc: 6, addr: reg.progPowerBase + slot, value: powerReg, encode: { kind: 'watt_scaled_u16', scale: powerScale, kw: dbattKw }, dwell_s: 900, min_change: 50, bench_pending: true },",
  "      { role: 'battery_target_soc', fc: 6, addr: reg.progSocBase + slot, value: targetSoc, encode: { kind: 'pct', direction: charging ? 'charge' : 'discharge' }, dwell_s: 900, min_change: 1, bench_pending: true },",
  "      { role: 'grid_charge_enable', fc: 6, addr: reg.progChargeBase + slot, value: chargeEnum, encode: { kind: 'charge_enum', eeg_gated: true, disabled: 0, grid: 1 }, dwell_s: 900, min_change: 0, bench_pending: true }",
  "    ];",
  "    if (pvLimitKw != null) { var capW = Math.max(0, pvLimitKw * 1000); dplanned.push({ role: 'pv_limit', fc: 6, addr: reg.exportLimit, value: Math.round(capW / reg.exportLimitScale) & 0xffff, encode: { kind: 'feed_in_cap_w', scale: reg.exportLimitScale, kw: pvLimitKw }, dwell_s: 900, min_change: 1, bench_pending: true }); }",
  "    dbase.planned = dplanned; return dbase;",
  "  }",
  "  if (tier === 1 && comm === 'fronius_solar_api') {",
  "    // Fronius SunSpec control (curtailment, Model 123 WMaxLimPct) is UNCERTIFIED",
  "    // -> planned only, NEVER executed. The Model 123 base is DISCOVERED live per",
  "    // device (sunspec/model-discovery.js); that walk I/O is not wired into the",
  "    // flow this increment, so without opts.sunspec there is no base -> planned",
  "    // stays EMPTY (never a fabricated address). Adapter 'fronius_sunspec' !=",
  "    // 'modbus_tcp', so the write/readback executor no-ops on it (like Deye).",
  "    var fport = Number(conn.control_port) > 0 ? Number(conn.control_port) : 502;",
  "    var funitId = Number(conn.control_unit_id) > 0 ? Number(conn.control_unit_id) : 1;",
  "    return { adapter: 'fronius_sunspec', family: family, target: ip + ':' + fport, connection: { ip: ip, port: fport, unit_id: funitId }, certified: certified, controlEnabled: controlEnabled, writes: [], readbacks: [], planned: [], reason: 'Fronius SunSpec: SunSpec-Modelle nicht erkannt (Steuerung nicht freigegeben)' };",
  "  }",
  "  return idle('unbekannte Kommunikationsmethode');",
  "}",
].join('\n');

// The plan driver: read the setpoint + the active selection, build the write
// plan. `selectionExpr` is the JS expression that yields the selection - the
// self-wiring auto tab reads flow.inverter_config; the Simulator tab hardcodes
// the sim's generic_modbus/sunspec selection.
const controlPlanFunc = (selectionExpr) => [
  "// Steuerung / Schreibplan - der Herzschlag der Selbstverdrahtung auf der",
  "// SCHREIB-Seite: nimmt den (bereits guard-begrenzten) Sollwert vom Core und",
  "// baut den Schreibplan fuer die aktive Auswahl. Traegt eine KOPIE von",
  "// controlRoute() aus edge-app/nodered/inverter-control-routing.js (synchron",
  "// gehalten, gepinnt von flows-sync.test.js). SICHERHEIT: schreibt NICHTS,",
  "// solange nicht control_enabled (Not-Aus des Core, Standard AUS) UND die",
  "// Familie zertifiziert ist ('sunspec'; Deye bleibt bis zur Pruefstand-Freigabe",
  "// nur lesend).",
  controlRouteSource,
  "var sp = msg.setpoint || null;",
  "if (!sp) { node.status({ fill: 'grey', shape: 'ring', text: 'kein Sollwert' }); return null; }",
  "var sel = " + selectionExpr + ";",
  "msg.control = controlRoute(sel, sp, {});",
  "if (msg.control.adapter === 'idle') { node.status({ fill: 'grey', shape: 'ring', text: msg.control.reason || 'keine Steuerung' }); return null; }",
  "var nWrites = msg.control.writes.length;",
  "node.status({ fill: nWrites ? 'blue' : 'grey', shape: 'dot', text: msg.control.family + ': ' + (nWrites ? (nWrites + ' Schreibbefehle') : (msg.control.reason || 'nur lesen')) });",
  "return msg;",
].join('\n');

// The executor: a single ordered Modbus-TCP connection performing the plan's
// FC6 writes then FC3 readbacks, comparing commanded-vs-actual per register and
// emitting the readback for vp-control-readback (report §5). Only the generic
// modbus_tcp (SunSpec) adapter is executed here; the Deye adapter carries no
// executable writes/readbacks (read-only until bench-certified) so it no-ops.
const controlExecFunc = [
  "// Steuerung schreiben + zuruecklesen (report Rueckleseschleife §5): eine",
  "// geordnete TCP-Verbindung, erst die FC6-Schreibbefehle, dann jedes Register",
  "// per FC3 zurueckgelesen und befohlen-gegen-tatsaechlich verglichen. Ergebnis",
  "// -> vp-control-readback (edge/control/readback, nicht retained). Nur der",
  "// generische SunSpec-Adapter schreibt hier; der Deye-Adapter traegt keine",
  "// ausfuehrbaren Befehle (nur lesend bis Pruefstand-Freigabe) und macht nichts.",
  "const net = global.get('net');",
  "if (!net) { node.status({ fill: 'red', shape: 'ring', text: 'net fehlt (settings.js)' }); node.error('functionGlobalContext.net in settings.js setzen', msg); return null; }",
  "const ctrl = msg.control;",
  "if (!ctrl || ctrl.adapter !== 'modbus_tcp' || !Array.isArray(ctrl.readbacks) || ctrl.readbacks.length === 0) {",
  "  node.status({ fill: 'grey', shape: 'ring', text: (ctrl && ctrl.reason) ? ctrl.reason : 'keine Steuerung' });",
  "  return null;",
  "}",
  "const conn = ctrl.connection || {};",
  "const unitId = conn.unit_id || 1;",
  "const timeoutMs = conn.timeout_ms || 5000;",
  "const s16 = (v) => { v &= 0xffff; return v > 0x7fff ? v - 0x10000 : v; };",
  "const frameLen = (buf) => (buf.length < 6 ? null : 6 + buf.readUInt16BE(4));",
  "const buildRead = (txid, addr, count) => { const b = Buffer.alloc(12); b.writeUInt16BE(txid & 0xffff, 0); b.writeUInt16BE(0, 2); b.writeUInt16BE(6, 4); b[6] = unitId & 0xff; b[7] = 0x03; b.writeUInt16BE(addr & 0xffff, 8); b.writeUInt16BE(count & 0xffff, 10); return b; };",
  "const buildWrite = (txid, addr, value) => { const b = Buffer.alloc(12); b.writeUInt16BE(txid & 0xffff, 0); b.writeUInt16BE(0, 2); b.writeUInt16BE(6, 4); b[6] = unitId & 0xff; b[7] = 0x06; b.writeUInt16BE(addr & 0xffff, 8); b.writeUInt16BE(value & 0xffff, 10); return b; };",
  "const parseRead = (buf, txid) => { if (buf.length < 9) throw new Error('Antwort zu kurz'); if (buf.readUInt16BE(0) !== (txid & 0xffff)) throw new Error('Transaktions-ID'); const fn = buf[7]; if (fn & 0x80) throw new Error('Modbus-Ausnahme 0x' + (buf[8] || 0).toString(16)); if (fn !== 0x03) throw new Error('Modbus-Funktion 0x' + fn.toString(16)); const bc = buf[8]; const regs = []; for (let i = 0; i < bc >> 1; i++) regs.push(buf.readUInt16BE(9 + i * 2)); return regs; };",
  "const parseWrite = (buf, txid) => { if (buf.length < 12) throw new Error('Schreibantwort zu kurz'); if (buf.readUInt16BE(0) !== (txid & 0xffff)) throw new Error('Transaktions-ID'); const fn = buf[7]; if (fn & 0x80) throw new Error('Modbus-Ausnahme 0x' + (buf[8] || 0).toString(16)); if (fn !== 0x06) throw new Error('Modbus-Funktion 0x' + fn.toString(16)); return { addr: buf.readUInt16BE(8), value: buf.readUInt16BE(10) }; };",
  "let txid = context.get('ctxid') || 0;",
  "return new Promise((resolve) => {",
  "  const sock = new net.Socket();",
  "  sock.setNoDelay(true);",
  "  let done = false, acc = Buffer.alloc(0), pending = null;",
  "  const finish = (err, okMsg) => { if (done) return; done = true; clearTimeout(t); try { sock.destroy(); } catch (e) { /* ignore */ } if (err) { node.status({ fill: 'red', shape: 'ring', text: 'Steuerung: ' + err.message }); resolve(null); } else { resolve(okMsg); } };",
  "  const t = setTimeout(() => finish(new Error('Timeout')), timeoutMs);",
  "  sock.once('error', (e) => finish(e));",
  "  const txn = (buf, parse) => new Promise((res, rej) => { pending = { parse, res, rej }; acc = Buffer.alloc(0); sock.write(buf); });",
  "  sock.on('data', (chunk) => { acc = Buffer.concat([acc, chunk]); const need = frameLen(acc); if (need !== null && acc.length >= need && pending) { const p = pending; pending = null; const frame = acc.slice(0, need); acc = acc.slice(need); try { p.res(p.parse(frame)); } catch (e) { p.rej(e); } } });",
  "  sock.connect(conn.port || 502, conn.ip, async () => {",
  "    try {",
  "      for (const w of (ctrl.writes || [])) { txid = (txid + 1) & 0xffff; const wt = txid; await txn(buildWrite(txid, w.addr, w.value), (b) => parseWrite(b, wt)); }",
  "      const registers = [];",
  "      for (const rb of ctrl.readbacks) { txid = (txid + 1) & 0xffff; const rt = txid; const regs = await txn(buildRead(txid, rb.addr, 1), (b) => parseRead(b, rt)); const actual = regs[0] & 0xffff; const tol = rb.tolerance || 0; const entry = { role: rb.role, fc: 3, addr: rb.addr, commanded_raw: rb.expect & 0xffff, actual_raw: actual, match: Math.abs(actual - (rb.expect & 0xffff)) <= tol }; if (rb.role === 'battery_power') { entry.commanded_kw = s16(rb.expect) / 100; entry.actual_kw = s16(actual) / 100; } if (rb.role === 'pv_limit') { entry.commanded_kw = (rb.expect & 0xffff) === 0xffff ? null : rb.expect / 100; entry.actual_kw = actual === 0xffff ? null : actual / 100; } registers.push(entry); }",
  "      context.set('ctxid', txid);",
  "      const all = registers.every((r) => r.match);",
  "      node.status({ fill: all ? 'green' : 'red', shape: 'dot', text: all ? ('bestätigt (' + registers.length + ')') : 'Abweichung' });",
  "      const sp = msg.setpoint || {};",
  "      msg.payload = { ts: new Date().toISOString(), family: ctrl.family, source: sp.source || '', slot_start: sp.slot_start, control_enabled: !!ctrl.controlEnabled, certified: !!ctrl.certified, registers: registers };",
  "      finish(null, msg);",
  "    } catch (e) { finish(e); }",
  "  });",
  "});",
].join('\n');

// embedModule - embed a repo module VERBATIM into a function-node body (a
// Node-RED flow cannot `require` a repo file at runtime); flows-sync.test.js
// pins each embed against the file, so editing a module without re-running
// build-flows.js fails there instead of shipping a stale copy.
const embedModule = (file) =>
  '(function () { var module = { exports: {} };\n' +
  fs.readFileSync(path.join(__dirname, file), 'utf8') +
  '\nreturn module.exports; })()';

// --- Additional-source read fan-out (multi-source Anlage, Phase 1) -----------
//
// The read-side sibling of the inverter self-wiring: a site can have ADDITIONAL
// read-only Erzeuger (PV) sources beyond the one battery-hybrid. vp-sources-config
// hands the retained list (edge/sources/config) to a store node; a poll reads each
// source and publishes its value on edge/sources/<id>/telemetry (vp-quelle /
// vp-netz), where the core SUMS Erzeuger PV into the composite site reading.
// SCOPE: the executor reads EVERY read transport in EVERY source slot -
// modbus_tcp sources (the compact sim profile the e2e uses), fronius_sunspec
// sources via the real SunSpec model-discovery walk (a separate AC-coupled PV,
// e.g. a Fronius Eco as an Erzeuger), goe_http_api sources (a go-e wallbox as a
// Consumer), solarman_v5 sources (a Deye over its Solarman-V5 logger) and
// fronius_solar_api sources (a Fronius over its Solar API v1). Read-only - there
// is NO setpoint/control path for a source. Filtering mirrors
// sources-routing.planSources; flows-sync.test.js pins it.
const sourcesStoreFunc = [
  "// Uebernimmt die im Edge-App-Portal hinzugefuegten zusaetzlichen Energiequellen",
  "// (retained auf edge/sources/config, von vp-sources-config geparst) und baut",
  "// daraus die kompakten Leseplaene. Drei nur-lesende Rollen: pv-generation",
  "// (Erzeuger), grid-meter (Netz-Zaehler) und consumer (Verbraucher, z. B. eine",
  "// go-e-Wallbox); der Leseplan traegt die Rolle, damit der Leser das richtige",
  "// Feld veroeffentlicht. Fuenf ausfuehrbare Adapter: modbus_tcp (kompaktes",
  "// Sim-Profil), fronius_sunspec -> sunspec_live (echte SunSpec-Modellerkennung",
  "// ueber Modbus TCP, z. B. eine Fronius-PV als Erzeuger), goe_http_api (go-e",
  "// Charger ueber ihre lokale HTTP-API, ein Verbraucher), solarman_v5 (eine Deye",
  "// als zusaetzliche Quelle ueber den Solarman-V5-Logger) und fronius_solar_api",
  "// (eine Fronius ueber ihre Solar API v1). Synchron gehalten mit",
  "// edge-app/nodered/sources-routing.js (planSources).",
  "// TRACE (echter Geraete-Bug 2026-07-13, Quelle lieferte weder Daten noch",
  "// Warnung): JEDE Routing-Entscheidung wird benannt - je Quelle ihr Adapter",
  "// oder ein lautes NICHT VERDRAHTET per node.warn - damit ein einziges",
  "// 'docker compose logs nodered' zeigt, ob und wie jede Quelle verdrahtet",
  "// wurde. Volles Detail bei jeder AENDERUNG; eine unveraenderte Konfiguration",
  "// (retained Redelivery bei Reconnect) loggt ratenbegrenzt (60 s) eine Zeile.",
  "const list = Array.isArray(msg.payload) ? msg.payload : [];",
  "const num = (v, d) => { const n = typeof v === 'string' ? Number(v.trim()) : v; return (typeof n === 'number' && isFinite(n)) ? n : d; };",
  "const MODBUS_PROFILES = { sunspec: { fc: 3, addr: 0, count: 9 } };",
  // The Deye register-map families with measurement registers (mirrors
  // deye-decode.FAMILIES / the DEYE_READS keys the primary router carries). The
  // reader computes the actual read blocks from the family; here we only gate.
  "const DEYE_FAMILIES = { string: true, hybrid_1p: true, hybrid_3p: true, micro: true };",
  "const GOE_STATUS_FILTER = 'nrg,car,alw,amp,wh';",
  "const FRONIUS_POWERFLOW_PATH = '/solar_api/v1/GetPowerFlowRealtimeData.fcgi';",
  "const plans = [];",
  "const notes = [];",
  "list.forEach((s, i) => {",
  "  if (!s || typeof s !== 'object') { notes.push({ warn: true, t: 'Quellen-Eintrag #' + (i + 1) + ' NICHT VERDRAHTET: kein Objekt' }); return; }",
  "  const id = (typeof s.id === 'string' && s.id) ? s.id : ('#' + (i + 1));",
  "  if (s.role !== 'pv-generation' && s.role !== 'grid-meter' && s.role !== 'consumer') { notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: unbekannte Rolle \"' + s.role + '\"' }); return; }",
  "  const conn = s.connection || {};",
  "  const ip = (typeof conn.ip === 'string' ? conn.ip : '').trim();",
  "  if (!ip) { notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: keine IP in der connection' }); return; }",
  "  if (s.communication === 'modbus_tcp') {",
  "    const read = MODBUS_PROFILES[s.family];",
  "    if (!read) { notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: unbekanntes modbus_tcp-Profil \"' + s.family + '\"' }); return; }",
  "    plans.push({ id: s.id, role: s.role, adapter: 'modbus_tcp', profile: s.family, conn: { ip, port: num(conn.port, 502), unit_id: num(conn.unit_id, 1) }, read: { fc: read.fc, addr: read.addr, count: read.count } });",
  "    notes.push({ t: 'Quelle ' + id + ' (' + s.role + '): modbus_tcp ' + ip + ':' + num(conn.port, 502) + ' -> Leseplan (Profil ' + s.family + ')' });",
  "  } else if (s.communication === 'fronius_sunspec') {",
  "    const modelType = (conn.model_type === 'float' || conn.model_type === 'int_sf') ? conn.model_type : 'auto';",
  "    plans.push({ id: s.id, role: s.role, adapter: 'sunspec_live', conn: { ip, port: num(conn.port, 502), unit_id: num(conn.unit_id, 1), invert_grid_sign: !!conn.invert_grid_sign, model_type: modelType } });",
  "    notes.push({ t: 'Quelle ' + id + ' (' + s.role + '): fronius_sunspec ' + ip + ':' + num(conn.port, 502) + ' -> Leseplan sunspec_live (unit ' + num(conn.unit_id, 1) + ', model_type ' + modelType + ')' });",
  "  } else if (s.communication === 'goe_http_api') {",
  "    const port = num(conn.port, 80);",
  "    plans.push({ id: s.id, role: s.role, adapter: 'goe_http_api', conn: { ip, port }, url: 'http://' + ip + ':' + port + '/api/status?filter=' + GOE_STATUS_FILTER });",
  "    notes.push({ t: 'Quelle ' + id + ' (' + s.role + '): goe_http_api ' + ip + ':' + port + ' -> Leseplan (go-e /api/status)' });",
  "  } else if (s.communication === 'solarman_v5') {",
  "    if (!DEYE_FAMILIES[s.family]) { notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: unbekannte Deye-Familie \"' + s.family + '\"' }); return; }",
  "    const serial = conn.serial;",
  "    if (serial === undefined || serial === null || serial === '' || !(Number(serial) > 0)) { notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: Datenlogger-Seriennummer fehlt (solarman_v5)' }); return; }",
  "    const port = num(conn.port, 8899);",
  "    plans.push({ id: s.id, role: s.role, adapter: 'solarman_v5', family: s.family, conn: { ip, port, serial, mb_slave_id: num(conn.mb_slave_id, 1), invert_grid_sign: !!conn.invert_grid_sign, invert_batt_sign: !!conn.invert_batt_sign, power_scale: num(conn.power_scale, 0) } });",
  "    notes.push({ t: 'Quelle ' + id + ' (' + s.role + '): solarman_v5 ' + ip + ':' + port + ' -> Leseplan (Deye-Familie ' + s.family + ')' });",
  "  } else if (s.communication === 'fronius_solar_api') {",
  "    const insecure = !!conn.insecure_tls;",
  "    const scheme = insecure ? 'https' : 'http';",
  "    const port = num(conn.port, 80);",
  "    plans.push({ id: s.id, role: s.role, adapter: 'fronius_solar_api', conn: { ip, port }, scheme, insecure_tls: insecure, invert_grid_sign: !!conn.invert_grid_sign, url: scheme + '://' + ip + ':' + port + FRONIUS_POWERFLOW_PATH });",
  "    notes.push({ t: 'Quelle ' + id + ' (' + s.role + '): fronius_solar_api ' + ip + ':' + port + ' -> Leseplan (Solar API v1)' });",
  "  } else {",
  "    notes.push({ warn: true, t: 'Quelle ' + id + ' NICHT VERDRAHTET: unbekannte Kommunikation \"' + s.communication + '\"' });",
  "  }",
  "});",
  "flow.set('source_plans', plans);",
  "const summary = 'Quellen-Konfiguration: ' + list.length + ' Eintrag/Eintraege -> ' + plans.length + ' Leseplan/-plaene';",
  "const sig = JSON.stringify(notes.map((n) => n.t));",
  "const now = Date.now();",
  "const changed = sig !== context.get('src_store_sig');",
  "if (changed || now - (context.get('src_store_log_at') || 0) >= 60000) {",
  "  context.set('src_store_sig', sig);",
  "  context.set('src_store_log_at', now);",
  "  node.log(summary + (changed ? '' : ' (unveraendert)'));",
  "  if (changed) notes.forEach((n) => { if (n.warn) node.warn(n.t); else node.log(n.t); });",
  "}",
  "const txt = plans.length + ' Quelle(n)';",
  "node.status({ fill: plans.length ? 'green' : 'grey', shape: plans.length ? 'dot' : 'ring', text: plans.length ? txt : 'keine Quellen' });",
  "return null;",
].join('\n');

const sourcesReadFunc = [
  "// Liest jede konfigurierte Quelle SEQUENZIELL (nie zwei Sockets gleichzeitig)",
  "// und sendet je Quelle eine Nachricht nach Rolle: Erzeuger {source_id, payload:",
  "// {pv_power_kw}} an vp-quelle (Ausgang 1), Netz-Zaehler {source_id, payload:",
  "// {power_kw}} (vorzeichenbehaftet, + Bezug / - Einspeisung) an vp-netz",
  "// (Ausgang 2). Zwei Adapter: modbus_tcp decodiert den kompakten SunSpec-",
  "// Sim-Block (KOPIE aus edge-app/nodered/modbus-tcp.js, Register 0 = Netz,",
  "// Register 1 = PV); sunspec_live (fronius_sunspec) laeuft die echte SunSpec-",
  "// Modellerkennung ueber EINGEBETTETE Kopien von sunspec/model-discovery.js +",
  "// sunspec/sunspec-live.js (ein Node-RED-Flow kann keine Repo-Datei requiren;",
  "// flows-sync.test.js pinnt die Einbettung) - je Lesung ein FRISCHER Reader mit",
  "// expliziten Timeouts, exakt der Aufruf aus test-read.js (der auf dem echten",
  "// Geraet nachweislich funktionierende 'Verbindung testen'-Pfad).",
  "// UEBERLAPPSCHUTZ (echter Geraete-Bug 2026-07-13): die volle SunSpec-",
  "// Modellerkennung auf einem echten Fronius Eco (viele sequenzielle FC3-",
  "// Roundtrips) kann laenger dauern als das 5-s-Poll-Intervall; ohne Schutz",
  "// stapelt jeder Tick eine WEITERE TCP-Verbindung auf dasselbe Geraet, dessen",
  "// Modbus-Gateway die laufende Verbindung dann kappt/verhungern laesst - KEIN",
  "// Walk wird je fertig ('Verbindung testen ok, Poll dauerhaft pending'). Ein",
  "// Tick, der auf einen noch laufenden Zyklus trifft, wird daher UEBERSPRUNGEN",
  "// (skip-if-busy; ein haengender Zyklus gilt nach 120 s als abgelaufen).",
  "// FEHLERISOLATION: eine tote Quelle wird uebersprungen (kein Send) - die",
  "// anderen liefern weiter, der Core zaehlt eine fehlende Quelle als abwesend",
  "// (nie als fabrizierte 0). NIE STILL: jedes fehlgeschlagene Lesen wird je",
  "// Quelle ratenbegrenzt (60 s) per node.warn benannt - damit im Log steht,",
  "// WARUM eine Quelle auf :8484 'pending' ist.",
  "// TRACE (echter Geraete-Bug 2026-07-13, Quelle lieferte weder Daten noch",
  "// Warnung): JEDE Poll-Entscheidung wird geloggt (node.log/node.warn ->",
  "// docker compose logs nodered) - keine Plaene / Tick uebersprungen /",
  "// Lesung gestartet / Ergebnis oder Fehler / veroeffentlicht. Identische",
  "// Wiederholungen sind je Schluessel auf eine Zeile pro 60 s begrenzt; ein",
  "// ZUSTANDSWECHSEL (ok -> Fehler, anderer Fehlergrund, andere Zaehler) loggt",
  "// IMMER sofort. NIE HAENGEN: jede Einzel-Lesung laeuft gegen ein hartes",
  "// Gesamt-Timeout (Promise.race, 30 s - weit ueber der erwarteten Walk-Dauer),",
  "// damit src_busy_since IMMER geleert wird und ein Haenger als geloggtes",
  "// Timeout endet, nie als dauerhaft stiller Skip.",
  'var __DISC = ' + embedModule('sunspec/model-discovery.js') + ';',
  'var __SS = ' + embedModule('sunspec/sunspec-live.js') + ';',
  'var __GOE = ' + embedModule('goe/goe-api.js') + ';',
  'var __SV5 = ' + embedModule('deye/solarman-v5.js') + ';',
  'var __DEYE = ' + embedModule('deye/deye-decode.js') + ';',
  'var __FR = ' + embedModule('fronius/solar-api.js') + ';',
  "const net = global.get('net');",
  "if (!net) { node.status({ fill: 'red', shape: 'ring', text: 'net fehlt (settings.js)' }); node.error('functionGlobalContext.net in settings.js setzen', msg); return null; }",
  "// http/https are needed only for the go-e (goe_http_api) + Fronius Solar API",
  "// (fronius_solar_api) branches; the modbus / sunspec / solarman branches do not",
  "// use them, so a missing global only fails those branches (with a named warn),",
  "// never the whole poll.",
  "const http = global.get('http');",
  "const https = global.get('https');",
  "const trace = (key, cls, line, isWarn) => {",
  "  const st = context.get('src_trace_' + key) || {};",
  "  const now = Date.now();",
  "  if (st.cls === cls && now - (st.at || 0) < 60000) return;",
  "  context.set('src_trace_' + key, { cls: cls, at: now });",
  "  if (isWarn) node.warn(line); else node.log(line);",
  "};",
  "const plans = flow.get('source_plans') || [];",
  "if (!plans.length) { node.status({ fill: 'grey', shape: 'ring', text: 'keine Quellen' }); trace('tick', 'noplans', 'Quellen-Poll: keine Leseplaene (source_plans leer) - nichts zu lesen'); return null; }",
  "const busySince = context.get('src_busy_since') || 0;",
  "if (busySince && Date.now() - busySince < 120000) { node.status({ fill: 'blue', shape: 'ring', text: 'Lesung laeuft noch - Tick uebersprungen' }); trace('tick', 'busy', 'Quellen-Poll: Tick uebersprungen - Lesung laeuft noch (seit ' + Math.round((Date.now() - busySince) / 1000) + ' s)'); return null; }",
  "context.set('src_busy_since', Date.now());",
  "const CONNECT_TIMEOUT_MS = 8000;",
  "const READ_TIMEOUT_MS = 8000;",
  "const SOURCE_OVERALL_TIMEOUT_MS = 30000;",
  "// MULTI-INVERTER AN EINER IP (Fronius Datamanager): mehrere Quellen mit",
  "// derselben IP und verschiedenen Unit-IDs laufen ohnehin STRENG SEQUENZIELL",
  "// durch diese Schleife (nie zwei Sockets gleichzeitig); zusaetzlich bekommt",
  "// ein traeges Single-Session-Gateway zwischen zwei Lesungen auf DIESELBE IP",
  "// eine kurze Atempause, damit es die gerade geschlossene Verbindung freigeben",
  "// kann, bevor die naechste oeffnet (ein refuse-newest-Gateway wuerde sonst",
  "// die zweite Quelle abweisen).",
  "const SAME_IP_GRACE_MS = 400;",
  "const withOverallTimeout = (p, ms) => Promise.race([p, new Promise((resolve) => setTimeout(() => resolve({ __overall_timeout: true }), ms))]);",
  "const warnFail = (plan, why) => {",
  "  trace('res_' + plan.id, 'fail:' + why, 'Quelle ' + plan.id + ' (' + plan.adapter + ' ' + plan.conn.ip + ':' + (plan.conn.port || 502) + '): ' + why, true);",
  "};",
  "const s16 = (v) => { v &= 0xffff; return v > 0x7fff ? v - 0x10000 : v; };",
  "const r3 = (x) => Math.round(x * 1000) / 1000;",
  "const frameLen = (buf) => (buf.length < 6 ? null : 6 + buf.readUInt16BE(4));",
  "const decodePv = (profile, regs) => {",
  "  if (profile === 'sunspec') { if (regs.length < 7) return null; return r3(s16(regs[1]) / 100); }",
  "  return null;",
  "};",
  "const decodeGrid = (profile, regs) => {",
  "  if (profile === 'sunspec') { if (regs.length < 7) return null; return r3(s16(regs[0]) / 100); }",
  "  return null;",
  "};",
  "const readOne = (plan, txid) => new Promise((resolve) => {",
  "  const conn = plan.conn; const unitId = conn.unit_id || 1; const timeoutMs = 5000;",
  "  const sock = new net.Socket(); sock.setNoDelay(true);",
  "  let done = false; let acc = Buffer.alloc(0);",
  "  const finish = (regs) => { if (done) return; done = true; try { sock.destroy(); } catch (e) { /* ignore */ } resolve(regs); };",
  "  const t = setTimeout(() => finish(null), timeoutMs);",
  "  const build = () => { const b = Buffer.alloc(12); b.writeUInt16BE(txid & 0xffff, 0); b.writeUInt16BE(0, 2); b.writeUInt16BE(6, 4); b[6] = unitId & 0xff; b[7] = 0x03; b.writeUInt16BE(plan.read.addr & 0xffff, 8); b.writeUInt16BE(plan.read.count & 0xffff, 10); return b; };",
  "  sock.once('error', () => { clearTimeout(t); finish(null); });",
  "  sock.connect(conn.port || 502, conn.ip, () => {",
  "    sock.on('data', (chunk) => {",
  "      acc = Buffer.concat([acc, chunk]);",
  "      const need = frameLen(acc);",
  "      if (need !== null && acc.length >= need) {",
  "        clearTimeout(t);",
  "        try { const buf = acc.slice(0, need); const fn = buf[7]; if (fn & 0x80 || fn !== 0x03) return finish(null); const bc = buf[8]; if (bc <= 0 || buf.length < 9 + bc) return finish(null); const regs = []; for (let i = 0; i < bc >> 1; i++) regs.push(buf.readUInt16BE(9 + i * 2)); finish(regs); } catch (e) { finish(null); }",
  "      }",
  "    });",
  "    sock.write(build());",
  "  });",
  "});",
  "// httpGet - ONE HTTP(S) GET returning parsed JSON, or null on any failure",
  "// (unreachable / timeout / non-JSON / HTTP>=400). Read-only; used by the go-e",
  "// branch. go-e is plain HTTP, so https is only a defensive fallback.",
  "const httpGet = (url) => new Promise((resolve) => {",
  "  const lib = (typeof url === 'string' && url.indexOf('https:') === 0) ? https : http;",
  "  if (!lib) return resolve(null);",
  "  let done = false; const finish = (v) => { if (done) return; done = true; resolve(v); };",
  "  let req;",
  "  try {",
  "    req = lib.request(url, { method: 'GET', timeout: 8000 }, (res) => {",
  "      if (res.statusCode >= 400) { res.resume(); return finish(null); }",
  "      let body = ''; res.setEncoding('utf8');",
  "      res.on('data', (c) => { body += c; if (body.length > 262144) { try { req.destroy(); } catch (e) { /* ignore */ } } });",
  "      res.on('end', () => { try { finish(JSON.parse(body)); } catch (e) { finish(null); } });",
  "    });",
  "  } catch (e) { return finish(null); }",
  "  req.on('error', () => finish(null));",
  "  req.on('timeout', () => { try { req.destroy(); } catch (e) { /* ignore */ } finish(null); });",
  "  req.end();",
  "});",
  "// readSolarmanReading - read ONE Deye source over the Solarman-V5 logger (TCP",
  "// 8899): a single ordered TCP connection, the family's read blocks sequentially",
  "// (the logger allows ONE client), then __DEYE.decode -> the canonical reading",
  "// { pv_power_kw, power_kw, load_kw, soc_pct }. Carries EMBEDDED copies of",
  "// deye/solarman-v5.js (__SV5) + deye/deye-decode.js (__DEYE). Read-only,",
  "// idle-safe: any framing/CRC/decode error or timeout -> null (never fabricated).",
  "const readSolarmanReading = (plan) => new Promise((resolve) => {",
  "  const conn = plan.conn;",
  "  const reads = __DEYE.planReads({ family: plan.family });",
  "  if (!reads || !reads.length) return resolve(null);",
  "  const sock = new net.Socket(); sock.setNoDelay(true);",
  "  let done = false; let acc = Buffer.alloc(0); let idx = 0; let seq = 1;",
  "  const blocks = [];",
  "  const finish = (v) => { if (done) return; done = true; try { sock.destroy(); } catch (e) { /* ignore */ } resolve(v); };",
  "  const t = setTimeout(() => finish(null), READ_TIMEOUT_MS);",
  "  const sendNext = () => { acc = Buffer.alloc(0); const r = reads[idx]; seq = (seq + 1) & 0xffff; sock.write(__SV5.buildReadRequest({ loggerSerial: conn.serial, sequence: seq, slaveId: conn.mb_slave_id || 1, startReg: r.start, count: r.count })); };",
  "  sock.once('error', () => { clearTimeout(t); finish(null); });",
  "  sock.connect(conn.port || 8899, conn.ip, () => {",
  "    sock.on('data', (chunk) => {",
  "      acc = Buffer.concat([acc, chunk]);",
  "      let need; try { need = __SV5.expectedFrameLength(acc); } catch (e) { clearTimeout(t); return finish(null); }",
  "      if (need === null || acc.length < need) return;",
  "      const r = reads[idx];",
  "      let block; try { block = __SV5.registerBlock(r.start, acc.slice(0, need), { expectLoggerSerial: conn.serial }); } catch (e) { clearTimeout(t); return finish(null); }",
  "      blocks.push(block); idx += 1;",
  "      if (idx < reads.length) { sendNext(); return; }",
  "      clearTimeout(t);",
  "      let out; try { out = __DEYE.decode(blocks, { family: plan.family, invert_grid_sign: !!conn.invert_grid_sign, invert_batt_sign: !!conn.invert_batt_sign, power_scale: conn.power_scale || 0 }); } catch (e) { return finish(null); }",
  "      finish(out && out.reading ? out : null);",
  "    });",
  "    sendNext();",
  "  });",
  "});",
  "// readFroniusReading - read ONE Fronius source over the Solar API v1: one",
  "// HTTP(S) GET on GetPowerFlowRealtimeData.fcgi, then __FR.decodePowerFlow ->",
  "// the canonical reading. Carries an EMBEDDED copy of fronius/solar-api.js",
  "// (__FR). Read-only, idle-safe: unreachable / timeout / non-JSON / HTTP>=400",
  "// / undecodable -> null (never fabricated 0).",
  "const readFroniusReading = (plan) => new Promise((resolve) => {",
  "  const lib = plan.scheme === 'https' ? https : http;",
  "  if (!lib) return resolve(null);",
  "  let done = false; const finish = (v) => { if (done) return; done = true; resolve(v); };",
  "  const opts = { method: 'GET', timeout: 8000 };",
  "  if (plan.scheme === 'https') opts.rejectUnauthorized = plan.insecure_tls ? false : true;",
  "  let req;",
  "  try {",
  "    req = lib.request(plan.url, opts, (res) => {",
  "      if (res.statusCode >= 400) { res.resume(); return finish(null); }",
  "      let body = ''; res.setEncoding('utf8');",
  "      res.on('data', (c) => { body += c; if (body.length > 262144) { try { req.destroy(); } catch (e) { /* ignore */ } } });",
  "      res.on('end', () => { let json; try { json = JSON.parse(body); } catch (e) { return finish(null); } let out; try { out = __FR.decodePowerFlow(json, { invertGridSign: !!plan.invert_grid_sign }); } catch (e) { return finish(null); } finish(out && out.reading ? out : null); });",
  "    });",
  "  } catch (e) { return finish(null); }",
  "  req.on('error', () => finish(null));",
  "  req.on('timeout', () => { try { req.destroy(); } catch (e) { /* ignore */ } finish(null); });",
  "  req.end();",
  "});",
  "let txid = context.get('stxid') || 0;",
  "return (async () => {",
  "  let ok = 0, fail = 0;",
  "  let prevIp = null;",
  "  const cycleStart = Date.now();",
  "  try {",
  "    for (const plan of plans) {",
  "      let pv = null, grid = null, load = null, why = '';",
  "      if (prevIp && plan.conn.ip === prevIp) { await new Promise((r) => setTimeout(r, SAME_IP_GRACE_MS)); }",
  "      prevIp = plan.conn.ip;",
  "      trace('start_' + plan.id, plan.adapter, 'Lese Quelle ' + plan.id + ' (' + plan.adapter + ' ' + plan.conn.ip + ':' + (plan.conn.port || 502) + ') ...');",
  "      if (plan.adapter === 'goe_http_api') {",
  "        if (!http || !https) { why = 'http/https fehlt (settings.js) - go-e nicht lesbar'; }",
  "        else {",
  "          const url = plan.url || __GOE.statusUrl(plan.conn.ip, plan.conn.port);",
  "          const json = await withOverallTimeout(httpGet(url), SOURCE_OVERALL_TIMEOUT_MS);",
  "          if (json && json.__overall_timeout) { why = 'Gesamt-Timeout nach ' + (SOURCE_OVERALL_TIMEOUT_MS / 1000) + ' s - Lesung abgebrochen (Verbindung haengt?)'; }",
  "          else { const dec = __GOE.decodeStatus(json); if (dec && dec.reading && typeof dec.reading.load_kw === 'number' && isFinite(dec.reading.load_kw)) load = dec.reading.load_kw; else why = 'keine go-e-Antwort / kein Ladewert (Timeout, Verbindung abgewiesen oder HTTP-API deaktiviert)'; }",
  "        }",
  "      } else if (plan.adapter === 'sunspec_live') {",
  "        const sunspecRead = __SS.makeSunspecReader({ net: net, discovery: __DISC, connectTimeoutMs: CONNECT_TIMEOUT_MS, readTimeoutMs: READ_TIMEOUT_MS });",
  "        const out = await withOverallTimeout(sunspecRead({ ip: plan.conn.ip, port: plan.conn.port, unitId: plan.conn.unit_id, invertGridSign: !!plan.conn.invert_grid_sign, modelType: plan.conn.model_type }).catch((e) => { why = 'SunSpec-Lesefehler: ' + (e && e.message ? e.message : e); return null; }), SOURCE_OVERALL_TIMEOUT_MS);",
  "        if (out && out.__overall_timeout) { why = 'Gesamt-Timeout nach ' + (SOURCE_OVERALL_TIMEOUT_MS / 1000) + ' s - Lesung abgebrochen (Verbindung haengt?)'; }",
  "        const reading = out && out.reading ? out.reading : null;",
  "        if (reading) {",
  "          if (typeof reading.pv_power_kw === 'number' && isFinite(reading.pv_power_kw)) pv = reading.pv_power_kw;",
  "          if (typeof reading.power_kw === 'number' && isFinite(reading.power_kw)) grid = reading.power_kw;",
  "        } else if (!why) { why = 'keine Antwort / kein SunSpec-Geraet (Timeout, Verbindung abgewiesen oder Walk abgebrochen)'; }",
  "      } else if (plan.adapter === 'solarman_v5') {",
  "        const out = await withOverallTimeout(readSolarmanReading(plan).catch((e) => { why = 'Deye-Lesefehler: ' + (e && e.message ? e.message : e); return null; }), SOURCE_OVERALL_TIMEOUT_MS);",
  "        if (out && out.__overall_timeout) { why = 'Gesamt-Timeout nach ' + (SOURCE_OVERALL_TIMEOUT_MS / 1000) + ' s - Lesung abgebrochen (Verbindung haengt?)'; }",
  "        const reading = out && out.reading ? out.reading : null;",
  "        if (reading) {",
  "          if (typeof reading.pv_power_kw === 'number' && isFinite(reading.pv_power_kw)) pv = reading.pv_power_kw;",
  "          if (typeof reading.power_kw === 'number' && isFinite(reading.power_kw)) grid = reading.power_kw;",
  "          if (typeof reading.load_kw === 'number' && isFinite(reading.load_kw)) load = reading.load_kw;",
  "        } else if (!why) { why = 'keine Antwort / kein Deye-Logger (Timeout, Verbindung abgewiesen oder falsche Seriennummer)'; }",
  "      } else if (plan.adapter === 'fronius_solar_api') {",
  "        if (!http || !https) { why = 'http/https fehlt (settings.js) - Fronius Solar API nicht lesbar'; }",
  "        else {",
  "          const out = await withOverallTimeout(readFroniusReading(plan), SOURCE_OVERALL_TIMEOUT_MS);",
  "          if (out && out.__overall_timeout) { why = 'Gesamt-Timeout nach ' + (SOURCE_OVERALL_TIMEOUT_MS / 1000) + ' s - Lesung abgebrochen (Verbindung haengt?)'; }",
  "          else { const reading = out && out.reading ? out.reading : null; if (reading) { if (typeof reading.pv_power_kw === 'number' && isFinite(reading.pv_power_kw)) pv = reading.pv_power_kw; if (typeof reading.power_kw === 'number' && isFinite(reading.power_kw)) grid = reading.power_kw; if (typeof reading.load_kw === 'number' && isFinite(reading.load_kw)) load = reading.load_kw; } else { why = 'keine Fronius-Antwort / keine Messwerte (Timeout, Verbindung abgewiesen oder Solar API deaktiviert)'; } }",
  "        }",
  "      } else {",
  "        txid = (txid + 1) & 0xffff;",
  "        const regs = await withOverallTimeout(readOne(plan, txid), SOURCE_OVERALL_TIMEOUT_MS);",
  "        if (Array.isArray(regs)) {",
  "          pv = decodePv(plan.profile, regs);",
  "          grid = decodeGrid(plan.profile, regs);",
  "        } else { why = (regs && regs.__overall_timeout) ? ('Gesamt-Timeout nach ' + (SOURCE_OVERALL_TIMEOUT_MS / 1000) + ' s - Lesung abgebrochen (Verbindung haengt?)') : 'keine Modbus-Antwort'; }",
  "      }",
  "      const ts = new Date().toISOString();",
  "      if (plan.role === 'grid-meter') {",
  "        if (grid === null || grid === undefined) { fail++; warnFail(plan, why || 'kein Netzwert in der Antwort'); continue; }",
  "        ok++;",
  "        node.send([null, { source_id: plan.id, payload: { power_kw: grid, ts } }, null]);",
  "        trace('res_' + plan.id, 'ok', 'Quelle ' + plan.id + ': power_kw=' + grid + ' -> veroeffentlicht auf edge/sources/' + plan.id + '/telemetry');",
  "      } else if (plan.role === 'consumer') {",
  "        if (load === null || load === undefined) { fail++; warnFail(plan, why || 'kein Verbrauchswert in der Antwort'); continue; }",
  "        ok++;",
  "        node.send([null, null, { source_id: plan.id, payload: { load_kw: load, ts } }]);",
  "        trace('res_' + plan.id, 'ok', 'Quelle ' + plan.id + ': load_kw=' + load + ' -> veroeffentlicht auf edge/sources/' + plan.id + '/telemetry');",
  "      } else {",
  "        if (pv === null || pv === undefined) { fail++; warnFail(plan, why || 'kein PV-Wert in der Antwort'); continue; }",
  "        ok++;",
  "        node.send([{ source_id: plan.id, payload: { pv_power_kw: pv, ts } }, null, null]);",
  "        trace('res_' + plan.id, 'ok', 'Quelle ' + plan.id + ': pv_power_kw=' + pv + ' -> veroeffentlicht auf edge/sources/' + plan.id + '/telemetry');",
  "      }",
  "    }",
  "    context.set('stxid', txid);",
  "    trace('cycle', ok + '/' + fail, 'Quellen-Zyklus: ' + ok + ' gelesen, ' + fail + ' fehlgeschlagen (' + (Date.now() - cycleStart) + ' ms)');",
  "    node.status({ fill: ok ? 'green' : (fail ? 'yellow' : 'grey'), shape: 'dot', text: ok + ' gelesen' + (fail ? (', ' + fail + ' ohne Antwort') : '') });",
  "  } finally {",
  "    context.set('src_busy_since', 0);",
  "  }",
  "  return null;",
  "})();",
].join('\n');

const SRCTAB = 'tab-sources';
const srcFn = (id, name, func, outputs, wires) => ({
  id, type: 'function', z: SRCTAB, name, func, outputs, noerr: 0, initialize: '', finalize: '', libs: [], x: 0, y: 0, wires,
});
const sourcesNodes = [
  {
    id: SRCTAB, type: 'tab', label: 'Energiequellen (automatisch)', disabled: false,
    info: [
      'ZUSAETZLICHE ENERGIEQUELLEN (Multi-Source): Neben dem einen',
      'Speicher-Wechselrichter (Tab "Wechselrichter (automatisch)") kann eine Anlage',
      'weitere NUR-LESENDE Quellen haben - eine separate AC-gekoppelte PV (Erzeuger),',
      'einen eigenen Zaehler am Netzuebergang (Netz-Zaehler) oder einen Verbraucher',
      '(z. B. eine go-e-Wallbox). Der Kunde fuegt sie im Edge-App-Webportal (:8484)',
      'hinzu; der Core veroeffentlicht die Liste retained (edge/sources/config). Dieser',
      'Tab liest jede Quelle und veroeffentlicht ihren Wert auf',
      'edge/sources/<id>/telemetry: eine Erzeuger-PV wird zur Gesamt-PV summiert, ein',
      'Netz-Zaehler ersetzt den Netzwert des Speicher-Wechselrichters, ein Verbraucher',
      'liefert seine Last (load_kw). OHNE Flow-Edit pro Kunde.',
      '',
      'Umfang: modbus_tcp-Quellen (kompaktes Sim-Profil), fronius_sunspec-Quellen',
      '(echte SunSpec-Modellerkennung ueber Modbus TCP, z. B. eine Fronius-PV als',
      'Erzeuger), goe_http_api-Quellen (go-e Charger ueber ihre lokale HTTP-API,',
      'ein Verbraucher), solarman_v5-Quellen (eine Deye ueber ihren Solarman-V5-',
      'Logger) und fronius_solar_api-Quellen (eine Fronius ueber ihre Solar API v1)',
      'werden gelesen. NUR LESEN - fuer eine Quelle gibt es keinen',
      'Steuerpfad. Routing/Codecs: sources-routing.js + modbus-tcp.js +',
      'sunspec/model-discovery.js + sunspec/sunspec-live.js + goe/goe-api.js +',
      'deye/solarman-v5.js + deye/deye-decode.js + fronius/solar-api.js',
      '(getestet; die Funktionsknoten tragen synchrone/eingebettete Kopien).',
    ].join('\n'),
  },
  {
    id: 'sources-note', type: 'comment', z: SRCTAB,
    name: 'Weitere Quellen auslesen: edge/sources/config -> je Quelle lesen -> edge/sources/<id>/telemetry (Erzeuger -> Gesamt-PV, Netz-Zaehler -> Netzwert)',
    info: '', x: 520, y: 40, wires: [],
  },
  {
    id: 'sources-cfg', type: 'vp-sources-config', z: SRCTAB, name: 'Quellen vom Core (retained)', core: 'cfg-vp-core',
    x: 200, y: 100, wires: [['sources-store']],
  },
  Object.assign(srcFn('sources-store', 'Quellen uebernehmen', sourcesStoreFunc, 1, [[]]), { x: 470, y: 100 }),
  {
    id: 'sources-poll', type: 'inject', z: SRCTAB, name: 'poll 5s',
    props: [{ p: 'payload' }], repeat: '5', crontab: '', once: true, onceDelay: '4',
    topic: '', payload: '', payloadType: 'date', x: 130, y: 180, wires: [['sources-read']],
  },
  Object.assign(srcFn('sources-read', 'Quellen lesen (sequenziell)', sourcesReadFunc, 3, [['sources-quelle'], ['sources-netz'], ['sources-verbraucher']]), { x: 420, y: 180 }),
  { id: 'sources-quelle', type: 'vp-quelle', z: SRCTAB, name: 'PV an VoltPilot Core', core: 'cfg-vp-core', x: 760, y: 150, wires: [] },
  { id: 'sources-netz', type: 'vp-netz', z: SRCTAB, name: 'Netz-Zaehler an VoltPilot Core', core: 'cfg-vp-core', x: 760, y: 200, wires: [] },
  { id: 'sources-verbraucher', type: 'vp-verbraucher', z: SRCTAB, name: 'Verbraucher an VoltPilot Core', core: 'cfg-vp-core', x: 760, y: 250, wires: [] },
];

// --- Verbindung testen (one-shot test-read) ----------------------------------
//
// The "Verbindung testen" button on :8484 posts an UNSAVED connection form to
// the core, which publishes it on edge/test-read/request (vp-test-request). This
// function reads the device ONCE with the SAME route()+decode the self-wiring
// poll uses and answers on edge/test-read/result (vp-test-result), correlated by
// request_id. It carries SYNCED COPIES of the decode modules + test-read.js by
// EMBEDDING the files verbatim (embedModule above); flows-sync.test.js pins them
// and test-read.test.js unit-tests the module. Read only - it opens a socket /
// one HTTP GET, never writes, never gates Speichern.

// The Fronius SunSpec-Modbus reader (real SunSpec discovery over Modbus TCP,
// port 502) for a Fronius Eco 27.0-3-S and any SunSpec-conformant inverter whose
// Solar API is unusable. It EMBEDS verbatim copies of sunspec/model-discovery.js
// (the walk) + sunspec/sunspec-live.js (the socket reader + measurement decode) -
// a Node-RED flow cannot `require` a repo file; flows-sync.test.js pins the
// embed. READ-ONLY (FC3), idle-safe (unreachable / no SunSpec device -> null).
const sunspecReadFunc = [
  '// Fronius SunSpec-Modbus lesen: echte SunSpec-Modellerkennung ueber Modbus TCP',
  '// (Port 502) - fuer Fronius-Wechselrichter, deren Solar API nicht funktioniert',
  '// (z. B. Eco 27.0-3-S). Traegt EINGEBETTETE Kopien von sunspec/model-discovery.js',
  '// + sunspec/sunspec-live.js (ein Node-RED-Flow kann keine Repo-Datei requiren;',
  '// flows-sync.test.js pinnt die Einbettung). Der Walker entdeckt die Modell-',
  '// Basisadresse LIVE und decodiert die Messwerte (Modell 111/112/113 float bzw.',
  '// 101/102/103 int+SF) -> pv_power_kw. NUR LESEN (FC3), schreibt nie. Idle-sicher:',
  '// unerreichbar / kein SunSpec-Geraet -> null (nie fabriziert). Ausgang 1:',
  '// Messwerte fuer vp-telemetrie; Ausgang 2: true als Link-Lebenszeichen.',
  '// UEBERLAPPSCHUTZ wie im Quellen-Poll: ein voller Walk auf einem echten',
  '// Geraet kann laenger als das 5-s-Poll-Intervall dauern - ein Tick, der auf',
  '// eine noch laufende Lesung trifft, wird uebersprungen statt eine zweite',
  '// Verbindung auf dasselbe Geraet zu stapeln (nach 120 s gilt eine haengende',
  '// Lesung als abgelaufen).',
  'var __DISC = ' + embedModule('sunspec/model-discovery.js') + ';',
  'var __SS = ' + embedModule('sunspec/sunspec-live.js') + ';',
  "var net = global.get('net');",
  "if (!net) { node.status({ fill: 'red', shape: 'ring', text: 'net fehlt (settings.js)' }); node.error('functionGlobalContext.net in settings.js setzen', msg); return null; }",
  'var s = msg.sunspec;',
  'if (!s || !s.conn || !s.conn.ip) return null;',
  'var conn = s.conn;',
  "var busySince = context.get('ss_busy_since') || 0;",
  "if (busySince && Date.now() - busySince < 120000) { node.status({ fill: 'blue', shape: 'ring', text: 'Lesung laeuft noch - Tick uebersprungen' }); return null; }",
  "context.set('ss_busy_since', Date.now());",
  "var warnFail = function (why) {",
  "  var last = context.get('ss_warn_at') || 0;",
  "  if (Date.now() - last < 60000) return;",
  "  context.set('ss_warn_at', Date.now());",
  "  node.warn('Fronius SunSpec (' + conn.ip + ':' + (conn.port || 502) + '): ' + why);",
  "};",
  'var read = __SS.makeSunspecReader({ net: net, discovery: __DISC, connectTimeoutMs: 8000, readTimeoutMs: 8000 });',
  'return read({ ip: conn.ip, port: conn.port, unitId: conn.unit_id, invertGridSign: !!conn.invert_grid_sign, modelType: conn.model_type }).then(function (out) {',
  "  context.set('ss_busy_since', 0);",
  "  if (!out || !out.reading) { node.status({ fill: 'yellow', shape: 'ring', text: 'keine SunSpec-Messwerte' }); warnFail('keine Antwort / kein SunSpec-Geraet (Timeout, Verbindung abgewiesen oder Walk abgebrochen)'); return null; }",
  '  var reading = Object.assign({ ts: new Date().toISOString() }, out.reading);',
  "  var pv = reading.pv_power_kw !== undefined ? reading.pv_power_kw.toFixed(1) : '?';",
  "  var st = (out.meta && out.meta.stLabel) ? (' (' + out.meta.stLabel + ')') : '';",
  "  node.status({ fill: 'green', shape: 'dot', text: 'pv ' + pv + ' kW' + st });",
  '  return [{ payload: reading }, { payload: true }];',
  "}).catch(function (e) { context.set('ss_busy_since', 0); node.status({ fill: 'red', shape: 'ring', text: 'SunSpec-Lesefehler' }); warnFail('SunSpec-Lesefehler: ' + (e && e.message ? e.message : e)); return null; });",
].join('\n');

const testReadFunc = [
  '// Verbindung testen (einmal lesen): liest die noch nicht gespeicherte Auswahl',
  '// EINMAL ueber denselben route()+decode wie der Selbstverdrahtungs-Poll und',
  '// klassifiziert das Ergebnis (ok / unreachable / no_answer / invalid_response',
  '// / implausible / fronius_api). Traegt SYNCHRON GEHALTENE Kopien der Decode-',
  '// Module + test-read.js (build-flows.js bettet die Dateien ein; flows-sync',
  '// pinnt sie, test-read.test.js testet sie). NUR LESEN - schreibt nie, gatet',
  '// nie das Speichern.',
  'var __SV5 = ' + embedModule('deye/solarman-v5.js') + ';',
  'var __DEYE = ' + embedModule('deye/deye-decode.js') + ';',
  'var __MB = ' + embedModule('modbus-tcp.js') + ';',
  'var __FR = ' + embedModule('fronius/solar-api.js') + ';',
  'var __DISC = ' + embedModule('sunspec/model-discovery.js') + ';',
  'var __SS = ' + embedModule('sunspec/sunspec-live.js') + ';',
  'var __GOE = ' + embedModule('goe/goe-api.js') + ';',
  'var __TR = ' + embedModule('test-read.js') + ';',
  "var net = global.get('net');",
  "var http = global.get('http');",
  "var https = global.get('https');",
  "if (!net || !http || !https) { node.status({ fill: 'red', shape: 'ring', text: 'net/http fehlt (settings.js)' }); node.error('functionGlobalContext.net/http/https in settings.js setzen', msg); return null; }",
  'var req = msg.payload;',
  "if (!req || typeof req.request_id !== 'string' || !req.request_id) { node.status({ fill: 'yellow', shape: 'ring', text: 'ungueltige Testanfrage' }); return null; }",
  '// Multi-Inverter-Suche (Fronius Datamanager): probe_units=true tastet dieselbe',
  '// Adresse nach WEITEREN Wechselrichter-Unit-IDs ab (1..10, ein SID-Read je ID,',
  '// begrenzt + nur lesend) statt einmal zu lesen - Datamanager-Konvention:',
  '// Wechselrichter-Nummer = Unit-ID. Idle-sicher: jeder Fehler wird klassifiziert.',
  'if (req.probe_units === true) {',
  '  var probeUnits = __TR.makeProbeUnits({ net: net });',
  "  node.status({ fill: 'blue', shape: 'dot', text: 'suche weitere Wechselrichter @ ' + ((req.connection && req.connection.ip) || '?') });",
  '  return probeUnits(req).then(function (res) {',
  "    res = res || { ok: false, error_code: 'invalid_response' };",
  '    res.request_id = req.request_id;',
  "    node.status({ fill: res.ok ? 'green' : 'yellow', shape: 'dot', text: res.ok ? ('gefunden: Unit-ID ' + ((res.found_units || []).join(', ') || 'keine')) : (res.error_code || 'Fehler') });",
  '    return { payload: res };',
  '  }).catch(function (e) {',
  "    node.status({ fill: 'red', shape: 'ring', text: 'Fehler: ' + (e && e.message) });",
  "    return { payload: { request_id: req.request_id, ok: false, error_code: 'invalid_response' } };",
  '  });',
  '}',
  'var readOnce = __TR.makeReadOnce({ deye: __DEYE, modbus: __MB, fronius: __FR, solarman: __SV5, sunspec: __SS, discovery: __DISC, goe: __GOE, net: net, http: http, https: https });',
  "node.status({ fill: 'blue', shape: 'dot', text: 'pruefe ' + (req.brand || req.communication || '?') });",
  'return readOnce(req, req.role).then(function (res) {',
  "  res = res || { ok: false, error_code: 'invalid_response' };",
  '  res.request_id = req.request_id;',
  "  node.status({ fill: res.ok ? 'green' : 'yellow', shape: 'dot', text: res.ok ? 'Verbindung ok' : (res.error_code || 'Fehler') });",
  '  return { payload: res };',
  '}).catch(function (e) {',
  "  node.status({ fill: 'red', shape: 'ring', text: 'Fehler: ' + (e && e.message) });",
  "  return { payload: { request_id: req.request_id, ok: false, error_code: 'invalid_response' } };",
  '});',
].join('\n');

const TESTTAB = 'tab-test';
const testNodes = [
  {
    id: TESTTAB, type: 'tab', label: 'Verbindung testen', disabled: false,
    info: [
      'VERBINDUNG TESTEN: der "Verbindung testen"-Button im Edge-App-Webportal',
      '(:8484) prueft eine NOCH NICHT GESPEICHERTE Wechselrichter-/Quellen-',
      'Verbindung. Der Core veroeffentlicht das Formular auf edge/test-read/request',
      '(nicht retained); dieser Tab liest das Geraet EINMAL ueber denselben',
      'route()+decode wie die Selbstverdrahtung und antwortet auf',
      'edge/test-read/result mit den decodierten Werten oder einem klassifizierten',
      'Fehler. NUR LESEN - schreibt nie, blockiert nie das Speichern.',
      '',
      'Routing/Decode: test-read.js + deye/*.js + modbus-tcp.js + fronius/*.js',
      '(getestet; der Funktionsknoten traegt eingebettete Kopien der Dateien,',
      'gepinnt von flows-sync.test.js).',
    ].join('\n'),
  },
  {
    id: 'test-note', type: 'comment', z: TESTTAB,
    name: 'edge/test-read/request -> einmal lesen (route + decode) -> edge/test-read/result',
    info: '', x: 470, y: 40, wires: [],
  },
  {
    id: 'test-request', type: 'vp-test-request', z: TESTTAB, name: 'Testanfrage vom Core', core: 'cfg-vp-core',
    x: 180, y: 120, wires: [['test-read']],
  },
  {
    id: 'test-read', type: 'function', z: TESTTAB, name: 'Verbindung testen (einmal lesen)', func: testReadFunc,
    outputs: 1, noerr: 0, initialize: '', finalize: '', libs: [], x: 470, y: 120, wires: [['test-result']],
  },
  {
    id: 'test-result', type: 'vp-test-result', z: TESTTAB, name: 'Ergebnis an Core', core: 'cfg-vp-core',
    x: 790, y: 120, wires: [],
  },
];

const fn = (id, name, func, outputs, wires) => ({
  id, type: 'function', z: TAB, name, func, outputs, noerr: 0, initialize: '', finalize: '', libs: [], x: 0, y: 0, wires,
});

const autoNodes = [
  {
    id: TAB, type: 'tab', label: 'Wechselrichter (automatisch)', disabled: false,
    info: [
      'SELBSTVERDRAHTUNG (Capstone): der Kunde waehlt seinen Wechselrichter EINMAL',
      'im Edge-App-Webportal (:8484 -> "Wechselrichter einrichten"); der Core',
      'veroeffentlicht die Auswahl retained auf dem lokalen Bus',
      '(edge/inverter/config). Dieser Tab liest sie und faehrt AUTOMATISCH den',
      'richtigen Leseadapter - OHNE Flow-Edit pro Kunde:',
      '',
      '  - Deye (communication=solarman_v5) -> Solarman-V5 ueber TCP 8899, mit der',
      '    gewaehlten family-Registerkarte (deye/deye-decode.js).',
      '  - Fronius (communication=fronius_solar_api) -> EIN HTTP-GET auf die lokale',
      '    Solar API (GetPowerFlowRealtimeData.fcgi, v1) - wie Home Assistant',
      '    (fronius/solar-api.js). Nur lesen, kein Modbus.',
      '  - Fronius (communication=fronius_sunspec) -> echte SunSpec-Modellerkennung',
      '    ueber Modbus TCP (Port 502) fuer Geraete ohne Solar API, z. B. Eco',
      '    27.0-3-S (sunspec/model-discovery.js + sunspec/sunspec-live.js). Nur lesen.',
      '  - alles andere (generic_modbus / modbus_tcp) -> Modbus-TCP ueber Port 502',
      '    mit dem gewaehlten Profil (modbus-tcp.js).',
      '',
      'Ohne Auswahl bleibt der Tab idle-sicher (kein Absturz). Nur Lesen/Monitoring',
      '- dieser Tab steuert NICHTS. Routing/Codecs: edge-app/nodered/',
      'inverter-routing.js + modbus-tcp.js + deye/*.js + fronius/solar-api.js',
      '(getestet, Quelle der Wahrheit; die Funktionsknoten tragen synchron',
      'gehaltene Kopien).',
    ].join('\n'),
  },
  {
    id: 'auto-note', type: 'comment', z: TAB,
    name: 'Vorne auswaehlen (Edge-App-Portal), hinten ist alles verdrahtet: edge/inverter/config -> passender Leseadapter',
    info: '', x: 470, y: 40, wires: [],
  },
  {
    id: 'auto-cfg', type: 'vp-inverter-config', z: TAB, name: 'Auswahl vom Core (retained)', core: 'cfg-vp-core',
    x: 190, y: 100, wires: [['auto-store']],
  },
  Object.assign(fn('auto-store', 'Auswahl uebernehmen', storeFunc, 1, [[]]), { x: 470, y: 100 }),
  {
    id: 'auto-poll', type: 'inject', z: TAB, name: 'poll 5s',
    props: [{ p: 'payload' }], repeat: '5', crontab: '', once: true, onceDelay: '3',
    topic: '', payload: '', payloadType: 'date', x: 130, y: 180, wires: [['auto-router']],
  },
  Object.assign(fn('auto-router', 'Router / Leseplan', routerFunc, 5, [['auto-solarman'], ['auto-modbus'], ['auto-fronius'], ['auto-sunspec'], ['auto-idle']]), { x: 320, y: 180 }),

  // Deye Solarman-V5 branch (verbatim reader + decoder)
  Object.assign(fn('auto-solarman', 'Solarman-V5 lesen (TCP 8899)', solarmanFunc, 1, [['auto-deye-decode']]), { x: 600, y: 140 }),
  Object.assign(fn('auto-deye-decode', 'Deye-Register -> Messwerte', deyeDecodeFunc, 2, [['auto-telemetrie'], ['auto-status', 'auto-linkwatch']]), { x: 600, y: 200 }),

  // Generic Modbus-TCP branch
  Object.assign(fn('auto-modbus', 'Modbus-TCP lesen (FC3)', modbusReadFunc, 1, [['auto-mb-decode']]), { x: 590, y: 280 }),
  Object.assign(fn('auto-mb-decode', 'Modbus-Register -> Messwerte', modbusDecodeFunc, 2, [['auto-telemetrie'], ['auto-status', 'auto-linkwatch']]), { x: 600, y: 340 }),

  // Fronius Solar API branch (HTTP reader + decoder, synced copy of fronius/solar-api.js)
  Object.assign(fn('auto-fronius', 'Fronius Solar API lesen (HTTP)', froniusReadFunc, 1, [['auto-fronius-decode']]), { x: 600, y: 400 }),
  Object.assign(fn('auto-fronius-decode', 'Fronius PowerFlow -> Messwerte', froniusDecodeFunc, 2, [['auto-telemetrie'], ['auto-status', 'auto-linkwatch']]), { x: 600, y: 460 }),

  // Fronius SunSpec-Modbus branch (real SunSpec discovery walk + measurement decode,
  // one node: read+decode+publish, embeds model-discovery.js + sunspec-live.js)
  Object.assign(fn('auto-sunspec', 'Fronius SunSpec lesen (Modbus TCP)', sunspecReadFunc, 2, [['auto-telemetrie'], ['auto-status', 'auto-linkwatch']]), { x: 600, y: 520 }),

  // Idle branch (status only, no publish)
  Object.assign(fn('auto-idle', 'untaetig (Statusanzeige)', idleFunc, 1, [[]]), { x: 600, y: 580 }),

  // Shared sinks
  { id: 'auto-telemetrie', type: 'vp-telemetrie', z: TAB, name: 'an VoltPilot Core', core: 'cfg-vp-core', x: 900, y: 180, wires: [] },
  { id: 'auto-status', type: 'vp-status', z: TAB, name: 'Wechselrichter-Status', core: 'cfg-vp-core', x: 920, y: 260, wires: [] },
  {
    id: 'auto-linkwatch', type: 'trigger', z: TAB, name: '15s ohne Messwert -> down',
    op1: '', op1type: 'nul', op2: 'false', op2type: 'bool', duration: '15', extend: true,
    overrideDelay: false, units: 's', reset: '', bytopic: 'all', topic: 'topic', outputs: 1,
    x: 640, y: 260, wires: [['auto-status']],
  },

  // --- Control path (write + readback), self-wired from the same selection ---
  // SAFETY: writes only happen for a certified family AND when the core's kill-
  // switch enabled the setpoint (control_enabled). A Deye selection routes here
  // too but stays read-only (controlRoute emits no executable writes).
  {
    id: 'auto-control-note', type: 'comment', z: TAB,
    name: 'Steuerung: Sollwert -> Schreibplan (controlRoute) -> schreiben + zuruecklesen -> vp-control-readback. Standard AUS (Not-Aus), Deye/Fronius nur lesend.',
    info: '', x: 520, y: 620, wires: [],
  },
  {
    id: 'auto-sollwert', type: 'vp-sollwert', z: TAB, name: 'Sollwert vom Core', core: 'cfg-vp-core',
    x: 140, y: 680, wires: [['auto-control-plan']],
  },
  Object.assign(fn('auto-control-plan', 'Steuerung / Schreibplan', controlPlanFunc("flow.get('inverter_config') || null"), 1, [['auto-control-exec']]), { x: 380, y: 680 }),
  Object.assign(fn('auto-control-exec', 'Steuerung schreiben + zuruecklesen', controlExecFunc, 1, [['auto-control-readback']]), { x: 650, y: 680 }),
  { id: 'auto-control-readback', type: 'vp-control-readback', z: TAB, name: 'Rueckmeldung an Core', core: 'cfg-vp-core', x: 930, y: 680, wires: [] },
];

// --- Simulator tab control path (the safe write->readback proof vs edge/sim) --
// Replaces the old sim-sp2reg/sim-write/sim-enable nodes: the same controlRoute
// + write/readback the real self-wiring path uses, but with the sim's fixed
// generic_modbus/sunspec selection (edge-sim:502). Proves reg 40/41/42
// write -> FC3 readback -> match against the UNCHANGED simulator (report §4.4a).
const simFn = (id, name, func, outputs, wires) => ({
  id, type: 'function', z: 'tab-sim', name, func, outputs, noerr: 0, initialize: '', finalize: '', libs: [], x: 0, y: 0, wires,
});
const SIM_SELECTION = "{ schema_version: '1.0', brand: 'generic_modbus', family: 'sunspec', communication: 'modbus_tcp', connection: { ip: 'edge-sim', port: 502, unit_id: 1 } }";
const simControlNodes = [
  {
    id: 'sim-control-note', type: 'comment', z: 'tab-sim',
    name: 'Steuerung + Rueckleseverifikation gegen den Simulator: FC6 Reg 40/41/42 schreiben, FC3 zuruecklesen, vergleichen',
    info: '', x: 380, y: 300, wires: [],
  },
  {
    id: 'sim-sollwert', type: 'vp-sollwert', z: 'tab-sim', name: 'Sollwert vom Core', core: 'cfg-vp-core',
    x: 140, y: 360, wires: [['sim-control-plan']],
  },
  Object.assign(simFn('sim-control-plan', 'Steuerung / Schreibplan', controlPlanFunc(SIM_SELECTION), 1, [['sim-control-exec']]), { x: 380, y: 360 }),
  Object.assign(simFn('sim-control-exec', 'Steuerung schreiben + zuruecklesen', controlExecFunc, 1, [['sim-control-readback']]), { x: 650, y: 360 }),
  { id: 'sim-control-readback', type: 'vp-control-readback', z: 'tab-sim', name: 'Rueckmeldung an Core', core: 'cfg-vp-core', x: 930, y: 360, wires: [] },
];

const simNodes = [simTab, ...simReadNodes, ...simControlNodes];

const flows = [...keepConfig, ...autoNodes, ...sourcesNodes, ...testNodes, ...simNodes];
fs.writeFileSync(OUT, JSON.stringify(flows, null, 2) + '\n');
console.log('flows.json written:', flows.length, 'nodes');
