package agent

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"
	"time"

	"git.tecmaxx.de/mamotec/voltpilot-ems/edge-app/core/internal/guards"
)

// controlReadbackVectors is docs/contracts/v2/control-readback-vectors.json:
// the Deye executor's readbacks as the core receives them after the palette
// node vp-control-readback (shape()), generated by
// edge-app/nodered/deye-control.e2e.test.js. The core reads the SAME file, so
// a field it parses but the palette never forwards is a red test here - not a
// silent field defect (Herzogau F11, 29.09.2026: mode "native", wrote and
// native* were dropped in the middle of the path).
type controlReadbackVectors struct {
	Schluessel   map[string][]string `json:"schluessel"`
	Unveraendert []string            `json:"unveraendert"`
	Faelle       []struct {
		Name    string         `json:"name"`
		Geformt map[string]any `json:"geformt"`
	} `json:"faelle"`
}

func loadControlReadbackVectors(t *testing.T) controlReadbackVectors {
	t.Helper()
	path := filepath.Join("..", "..", "..", "..", "docs", "contracts", "v2",
		"control-readback-vectors.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("contract vectors: %v", err)
	}
	var v controlReadbackVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("contract vectors: %v", err)
	}
	if len(v.Faelle) == 0 || len(v.Schluessel[""]) == 0 {
		t.Fatal("the contract vectors carry no cases")
	}
	return v
}

// readbackVector is the shaped readback `name` as it arrives on
// edge/control/readback, stamped `at` (the freshness rules key on ts);
// `override` replaces top-level fields.
func readbackVector(t *testing.T, name string, at time.Time, override map[string]any) []byte {
	t.Helper()
	for _, f := range loadControlReadbackVectors(t).Faelle {
		if f.Name != name {
			continue
		}
		m := map[string]any{}
		for k, v := range f.Geformt {
			m[k] = v
		}
		m["ts"] = at.Format(time.RFC3339Nano)
		for k, v := range override {
			m[k] = v
		}
		raw, err := json.Marshal(m)
		if err != nil {
			t.Fatal(err)
		}
		return raw
	}
	t.Fatalf("contract vectors: no case %q", name)
	return nil
}

// Every JSON name the core reads from a primary control readback must be one
// the palette can forward - the fixed list in the middle of the path is where
// the native proof went missing, while both ends had been extended.
func TestControlReadbackReadsOnlyWhatThePaletteForwards(t *testing.T) {
	v := loadControlReadbackVectors(t)
	var walk func(typ reflect.Type, prefix string)
	walk = func(typ reflect.Type, prefix string) {
		for i := 0; i < typ.NumField(); i++ {
			f := typ.Field(i)
			name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
			path := name
			if prefix != "" {
				path = prefix + "." + name
			}
			if name == "" || name == "-" {
				t.Fatalf("%s: %s has no JSON name", prefix, f.Name)
			}
			if !slices.Contains(v.Schluessel[prefix], name) {
				t.Errorf("the core reads %q, but vp-control-readback never forwards it", path)
			}
			if slices.Contains(v.Unveraendert, path) {
				continue // forwarded verbatim
			}
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				walk(ft, path)
			}
		}
	}
	walk(reflect.TypeOf(controlReadbackMsg{}), "")
}

// The productive E↓ proof (K3/K4b) rides the same path. Before 29.09.2026 it
// never reached nativeEvidence, so every covering slot the device took over
// was taken back after the grace (nachweis_fehlt). Through the palette it now
// proves the hand-over with the device's grid-charge answer and reports the
// certified levers; before the hand-over the precondition answers, and the
// Herzogau setting is refused by name.
func TestNativeEvidenceArrivesThroughThePalette(t *testing.T) {
	now := time.Now().UTC()
	a, _, _ := gridRig(t, now)

	a.onControlReadback("", readbackVector(t, "e_ab_takt1_konfiguration_lesen", now, nil))
	c := a.State.Get().Control
	proven, _, gcb := nativeEvidence(c, now, time.Minute)
	if proven || gcb == nil || !*gcb {
		t.Fatalf("before the hand-over: no proof, the precondition answers: %v %v %+v", proven, gcb, c)
	}
	if l := nativeLevers(c); l == nil || !l.Has(guards.NativeIntentCoverLoad) || l.Window || l.Persistent {
		t.Fatalf("the certified levers are reported on every cycle: %+v", l)
	}

	a.onControlReadback("", readbackVector(t, "e_ab_takt2_uebergabe", now, nil))
	c = a.State.Get().Control
	proven, intent, gcb := nativeEvidence(c, now, time.Minute)
	if !proven || intent != guards.NativeIntentCoverLoad || gcb == nil || !*gcb {
		t.Fatalf("the hand-over is proven with the in-mode answer: %v %q %v %+v", proven, intent, gcb, c)
	}
	a.onControlReadback("", readbackVector(t, "e_ab_takt3_nur_lesen", now, nil))
	if proven, _, _ := nativeEvidence(a.State.Get().Control, now, time.Minute); !proven {
		t.Fatal("a read-only native cycle keeps proving the mode")
	}

	a.onControlReadback("", readbackVector(t, "e_ab_herzogau_selling_first", now, nil))
	c = a.State.Get().Control
	if proven, _, _ := nativeEvidence(c, now, time.Minute); proven || !strings.Contains(c.NativeRefusal, "Selling First") {
		t.Fatalf("Herzogau: refused, and the core hears why: %+v", c)
	}
}
